-- do not edit; automatically generated by UU_AG
module AGtry where

import UU_Pretty
import Auxiliaries
import Classification
import Typology
import CC_aux


mkCtxAG :: [(Context,(Gens,Morphisms))] -> String -> Classification (Context,(Gens,Morphisms))
mkCtxAG ctxs ctxName
 = if null ctTrees
   then error ("!Error of type 0: unknown context "++ctxName
               ++".\ntesting: length ctxs="++show (length ctxs)
               ++if length ctxs>1
                 then ".\nPick one of "++chain ", " (map (name.fst) (tail ctxs))++" or "++(name.fst.head) ctxs
                 else if null ctxs then "No context available" else ".\nPick "++(name.fst.head) ctxs
              ) else
   head ctTrees
   where
    ctTrees = [t|tree<-trees, t<-locatesF ((==ctxName).name.fst) tree]
-- multiple ctTrees may occur if contexts are used multiply in different ctTrees.
    trees = makeClassificationsF (name.fst) tuples++[Cl s []| s<-singles]
            where tuples = [ ((spc,(mG,mD)),(gen,(mG',mD')))
                           | (spc@(Ctx nm on isa gE world dc ms cs),(mG,mD))<-ctxs, o<-on,(gen,(mG',mD'))<-ctxs,name gen==o]
                  singles= [ (spc,(mG,mD))
                           | (spc,(mG,mD))<-ctxs, not (name spc `elem` rd [name c|(s,g)<-tuples, (c,m)<-[s,g]])]
-- Architecture ------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      cs                   : [Context]
      sErr                 : [String]

-}
{-
   local variables for Architecture.Arch:

-}
-- semantic domain
type T_Architecture = (([Context]),([String]))
-- cata
sem_Architecture :: (Architecture) ->
                    (T_Architecture)
sem_Architecture ((Arch (_cs))) =
    (sem_Architecture_Arch ((sem_Contexts (_cs))))
sem_Architecture_Arch :: (T_Contexts) ->
                         (T_Architecture)
sem_Architecture_Arch (_cs) =
    let ( _cs_contexts,_cs_over,_cs_sErr) =
            (_cs (_cs_over))
    in  (_cs_contexts,_cs_sErr)
-- Concept -----------------------------------------------------
{-
   inherited attributes:
      cDef                 : Concepts

   chained attributes:

   synthesised attributes:
      concept              : Concept
      nm                   : String

-}
{-
   local variables for Concept.C:

-}
-- semantic domain
type T_Concept = (Concepts) ->
                 ((Concept),(String))
-- cata
sem_Concept :: (Concept) ->
               (T_Concept)
sem_Concept ((C (_c) (_os))) =
    (sem_Concept_C (_c) (_os))
sem_Concept_C :: (String) ->
                 ([String]) ->
                 (T_Concept)
sem_Concept_C (_c) (_os) (_lhs_cDef) =
    let 
    in  (head ([C nm os | C nm os <- _lhs_cDef, nm == _c]++[C _c []]),_c)
-- ConceptDef --------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      c                    : ConceptDef

-}
{-
   local variables for ConceptDef.Cd:

-}
-- semantic domain
type T_ConceptDef = ((ConceptDef))
-- cata
sem_ConceptDef :: (ConceptDef) ->
                  (T_ConceptDef)
sem_ConceptDef ((Cd (_pos) (_nm) (_def) (_ref))) =
    (sem_ConceptDef_Cd (_pos) (_nm) (_def) (_ref))
sem_ConceptDef_Cd :: (FilePos) ->
                     (String) ->
                     (String) ->
                     (String) ->
                     (T_ConceptDef)
sem_ConceptDef_Cd (_pos) (_nm) (_def) (_ref) =
    let 
    in  (Cd _pos _nm _def _ref)
-- ConceptDefs -------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      list                 : [ConceptDef]

-}
{-
   local variables for ConceptDefs.Cons:

-}
{-
   local variables for ConceptDefs.Nil:

-}
-- semantic domain
type T_ConceptDefs = (([ConceptDef]))
-- cata
sem_ConceptDefs :: (ConceptDefs) ->
                   (T_ConceptDefs)
sem_ConceptDefs (list) =
    (foldr (sem_ConceptDefs_Cons) (sem_ConceptDefs_Nil) ((map sem_ConceptDef list)))
sem_ConceptDefs_Cons :: (T_ConceptDef) ->
                        (T_ConceptDefs) ->
                        (T_ConceptDefs)
sem_ConceptDefs_Cons (_hd) (_tl) =
    let ( _hd_c) =
            (_hd )
        ( _tl_list) =
            (_tl )
    in  (_hd_c : _tl_list)
sem_ConceptDefs_Nil :: (T_ConceptDefs)
sem_ConceptDefs_Nil  =
    let 
    in  ([])
-- Concepts ----------------------------------------------------
{-
   inherited attributes:
      cDef                 : Concepts

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Concepts.Cons:

-}
{-
   local variables for Concepts.Nil:

-}
-- semantic domain
type T_Concepts = (Concepts) ->
                  ()
-- cata
sem_Concepts :: (Concepts) ->
                (T_Concepts)
sem_Concepts (list) =
    (foldr (sem_Concepts_Cons) (sem_Concepts_Nil) ((map sem_Concept list)))
sem_Concepts_Cons :: (T_Concept) ->
                     (T_Concepts) ->
                     (T_Concepts)
sem_Concepts_Cons (_hd) (_tl) (_lhs_cDef) =
    let ( _hd_concept,_hd_nm) =
            (_hd (_lhs_cDef))
    in  ()
sem_Concepts_Nil :: (T_Concepts)
sem_Concepts_Nil (_lhs_cDef) =
    let 
    in  ()
-- Context -----------------------------------------------------
{-
   inherited attributes:
      ctxTree              : Classification (Context,(Gens,Morphisms))
      ctxs                 : [(Context,(Gens,Morphisms))]

   chained attributes:

   synthesised attributes:
      context              : Context
      over                 : (Context,(Gens,Morphisms))
      sErr                 : [String]

-}
{-
   local variables for Context.Ctx:
      ctx
      cD
      genE
      inh
      mGen
      mD

-}
-- semantic domain
type T_Context = (Classification (Context,(Gens,Morphisms))) ->
                 ([(Context,(Gens,Morphisms))]) ->
                 ((Context),((Context,(Gens,Morphisms))),([String]))
-- cata
sem_Context :: (Context) ->
               (T_Context)
sem_Context ((Ctx (_nm) (_on) (_isa) (_gE) (_world) (_dc) (_ms) (_cs))) =
    (sem_Context_Ctx (_nm) (_on) (_isa) (_gE) (_world) ((sem_Patterns (_dc))) ((sem_Morphisms (_ms))) ((sem_ConceptDefs (_cs))))
sem_Context_Ctx :: (String) ->
                   ([String]) ->
                   (Inheritance Concept) ->
                   (GenR) ->
                   ([Classification Context]) ->
                   (T_Patterns) ->
                   (T_Morphisms) ->
                   (T_ConceptDefs) ->
                   (T_Context)
sem_Context_Ctx (_nm) (_on) (_isa) (_gE) (_world) (_dc) (_ms) (_cs) (_lhs_ctxTree) (_lhs_ctxs) =
    let (_mD) =
            (concat) [mD| (ctx,(mG,mD)) <- preCl _lhs_ctxTree]
        (_mGen) =
            (rd.concat) [mG| (ctx,(mG,mD)) <- preCl _lhs_ctxTree]
        (_inh) =
            Isa [(g,s)|G g s<- _mGen] (concs _mD>-rd [c|G g s<- _mGen, c<-[g,s]])
        (_genE) =
            genEq (typology _inh)
        (_cD) =
            makeConceptSpace _mD
        (_ctx) =
            Ctx _nm _on _inh _genE [] _dc_patterns _ms_list _cs_list
        ( _dc_conDefs,_dc_mGen,_dc_morphisms,_dc_nr,_dc_patterns,_dc_sErr) =
            (_dc (_cD) (_genE) (_mD) (0))
        ( _ms_list,_ms_sErr) =
            (_ms (_cD))
        ( _cs_list) =
            (_cs )
    in  (Ctx _nm _on _inh _genE [cl|Cl r cls<-[mapCl fst _lhs_ctxTree], cl<-cls]
             _dc_patterns _ms_list (sort' name (rd (_cs_list ++ _dc_conDefs)))
        ,(_ctx,(_dc_mGen,_ms_list ++ _dc_morphisms))
        ,_dc_sErr
        )
-- Contexts ----------------------------------------------------
{-
   inherited attributes:
      ctxs                 : [(Context,(Gens,Morphisms))]

   chained attributes:

   synthesised attributes:
      contexts             : Contexts
      over                 : [(Context,(Gens,Morphisms))]
      sErr                 : [String]

-}
{-
   local variables for Contexts.Cons:

-}
{-
   local variables for Contexts.Nil:

-}
-- semantic domain
type T_Contexts = ([(Context,(Gens,Morphisms))]) ->
                  ((Contexts),([(Context,(Gens,Morphisms))]),([String]))
-- cata
sem_Contexts :: (Contexts) ->
                (T_Contexts)
sem_Contexts (list) =
    (foldr (sem_Contexts_Cons) (sem_Contexts_Nil) ((map sem_Context list)))
sem_Contexts_Cons :: (T_Context) ->
                     (T_Contexts) ->
                     (T_Contexts)
sem_Contexts_Cons (_hd) (_tl) (_lhs_ctxs) =
    let ( _hd_context,_hd_over,_hd_sErr) =
            (_hd (mkCtxAG _lhs_ctxs (name _hd_context)) (_lhs_ctxs))
        ( _tl_contexts,_tl_over,_tl_sErr) =
            (_tl (_lhs_ctxs))
    in  (_hd_context : _tl_contexts,_hd_over : _tl_over,_hd_sErr ++ _tl_sErr)
sem_Contexts_Nil :: (T_Contexts)
sem_Contexts_Nil (_lhs_ctxs) =
    let 
    in  ([],[],[])
-- Drecords ----------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Drecords.Cons:

-}
{-
   local variables for Drecords.Nil:

-}
-- semantic domain
type T_Drecords = ()
-- cata
sem_Drecords :: (Drecords) ->
                (T_Drecords)
sem_Drecords (list) =
    (foldr (sem_Drecords_Cons) (sem_Drecords_Nil) (list))
sem_Drecords_Cons :: (Drecord) ->
                     (T_Drecords) ->
                     (T_Drecords)
sem_Drecords_Cons (_hd) (_tl) =
    let 
    in  ()
sem_Drecords_Nil :: (T_Drecords)
sem_Drecords_Nil  =
    let 
    in  ()
-- Factor ------------------------------------------------------
{-
   inherited attributes:
      cDef                 : Concepts
      gE                   : GenR
      isign                : [(Concept,Concept)]
      mDef                 : Morphisms

   chained attributes:

   synthesised attributes:
      factor               : Factor
      sErr                 : [String]
      signs                : [(Concept,Concept)]

-}
{-
   local variables for Factor.F:

-}
{-
   local variables for Factor.Fi:

-}
{-
   local variables for Factor.Fu:

-}
-- semantic domain
type T_Factor = (Concepts) ->
                (GenR) ->
                ([(Concept,Concept)]) ->
                (Morphisms) ->
                ((Factor),([String]),([(Concept,Concept)]))
-- cata
sem_Factor :: (Factor) ->
              (T_Factor)
sem_Factor ((F (_ts) (_sgn))) =
    (sem_Factor_F ((sem_Terms (_ts))) (_sgn))
sem_Factor ((Fi (_fs) (_sgn))) =
    (sem_Factor_Fi ((sem_Factors (_fs))) (_sgn))
sem_Factor ((Fu (_fs) (_sgn))) =
    (sem_Factor_Fu ((sem_Factors (_fs))) (_sgn))
sem_Factor_F :: (T_Terms) ->
                ((Concept,Concept)) ->
                (T_Factor)
sem_Factor_F (_ts) (_sgn) (_lhs_cDef) (_lhs_gE) (_lhs_isign) (_lhs_mDef) =
    let ( _ts_list,_ts_sErr,_ts_signs) =
            (_ts (_lhs_cDef) (_lhs_gE) (_lhs_isign) (_lhs_mDef))
    in  (F _ts_list (source _ts_list, target _ts_list),_ts_sErr,_ts_signs)
sem_Factor_Fi :: (T_Factors) ->
                 ((Concept,Concept)) ->
                 (T_Factor)
sem_Factor_Fi (_fs) (_sgn) (_lhs_cDef) (_lhs_gE) (_lhs_isign) (_lhs_mDef) =
    let ( _fs_list,_fs_sErr,_fs_signs) =
            (_fs (_lhs_cDef) (_lhs_gE) (_lhs_isign) (_lhs_mDef))
    in  (Fi _fs_list (foldr1 (lub _lhs_gE) (map source _fs_list), foldr1 (lub _lhs_gE) (map target _fs_list)),_fs_sErr,_fs_signs)
sem_Factor_Fu :: (T_Factors) ->
                 ((Concept,Concept)) ->
                 (T_Factor)
sem_Factor_Fu (_fs) (_sgn) (_lhs_cDef) (_lhs_gE) (_lhs_isign) (_lhs_mDef) =
    let ( _fs_list,_fs_sErr,_fs_signs) =
            (_fs (_lhs_cDef) (_lhs_gE) (_lhs_isign) (_lhs_mDef))
    in  (Fu _fs_list (foldr1 (lub _lhs_gE) (map source _fs_list), foldr1 (lub _lhs_gE) (map target _fs_list)),_fs_sErr,_fs_signs)
-- Factors -----------------------------------------------------
{-
   inherited attributes:
      cDef                 : Concepts
      gE                   : GenR
      isign                : [(Concept,Concept)]
      mDef                 : Morphisms

   chained attributes:

   synthesised attributes:
      list                 : Factors
      sErr                 : [String]
      signs                : [(Concept,Concept)]

-}
{-
   local variables for Factors.Cons:
      sgn

-}
{-
   local variables for Factors.Nil:

-}
-- semantic domain
type T_Factors = (Concepts) ->
                 (GenR) ->
                 ([(Concept,Concept)]) ->
                 (Morphisms) ->
                 ((Factors),([String]),([(Concept,Concept)]))
-- cata
sem_Factors :: (Factors) ->
               (T_Factors)
sem_Factors (list) =
    (foldr (sem_Factors_Cons) (sem_Factors_Nil) ((map sem_Factor list)))
sem_Factors_Cons :: (T_Factor) ->
                    (T_Factors) ->
                    (T_Factors)
sem_Factors_Cons (_hd) (_tl) (_lhs_cDef) (_lhs_gE) (_lhs_isign) (_lhs_mDef) =
    let (_sgn) =
            if null _tl_signs
            then if null _hd_signs
                 then []
                 else _hd_signs
            else if null _hd_signs
                 then _tl_signs
                 else rd [ (lub _lhs_gE a' a, lub _lhs_gE b' b)
                         | (a,b) <- _hd_signs, (a',b') <- _tl_signs
                         , order _lhs_gE a a', order _lhs_gE b b']
        ( _hd_factor,_hd_sErr,_hd_signs) =
            (_hd (_lhs_cDef) (_lhs_gE) (_lhs_isign) (_lhs_mDef))
        ( _tl_list,_tl_sErr,_tl_signs) =
            (_tl (_lhs_cDef) (_lhs_gE) (_lhs_isign) (_lhs_mDef))
    in  (_hd_factor : _tl_list
        ,["4 in "++show (pos (head _tl_list))++"\n   Incompatible concepts in comparing\n   "++
           show _hd_factor++show _hd_signs++" and\n   "++show (head _tl_list)++show _tl_signs
         | not (null _tl_list), null _sgn
         , (a,b)<- rd ([ (b, b') | (a,b) <- _hd_signs, (a',b') <- _tl_signs, not (order _lhs_gE b b')]++
                       [ (a, a') | (a,b) <- _hd_signs, (a',b') <- _tl_signs, not (order _lhs_gE a a')] )
         ]++ _hd_sErr ++ _tl_sErr
        ,if null _tl_list then _hd_signs else _sgn
        )
sem_Factors_Nil :: (T_Factors)
sem_Factors_Nil (_lhs_cDef) (_lhs_gE) (_lhs_isign) (_lhs_mDef) =
    let 
    in  ([],[],[])
-- Gen ---------------------------------------------------------
{-
   inherited attributes:
      cDef                 : Concepts

   chained attributes:

   synthesised attributes:
      gen                  : Gen

-}
{-
   local variables for Gen.G:

-}
-- semantic domain
type T_Gen = (Concepts) ->
             ((Gen))
-- cata
sem_Gen :: (Gen) ->
           (T_Gen)
sem_Gen ((G (_genus) (_spec))) =
    (sem_Gen_G ((sem_Concept (_genus))) ((sem_Concept (_spec))))
sem_Gen_G :: (T_Concept) ->
             (T_Concept) ->
             (T_Gen)
sem_Gen_G (_genus) (_spec) (_lhs_cDef) =
    let ( _genus_concept,_genus_nm) =
            (_genus (_lhs_cDef))
        ( _spec_concept,_spec_nm) =
            (_spec (_lhs_cDef))
    in  (G _genus_concept _spec_concept)
-- Gens --------------------------------------------------------
{-
   inherited attributes:
      cDef                 : Concepts

   chained attributes:

   synthesised attributes:
      list                 : Gens

-}
{-
   local variables for Gens.Cons:

-}
{-
   local variables for Gens.Nil:

-}
-- semantic domain
type T_Gens = (Concepts) ->
              ((Gens))
-- cata
sem_Gens :: (Gens) ->
            (T_Gens)
sem_Gens (list) =
    (foldr (sem_Gens_Cons) (sem_Gens_Nil) ((map sem_Gen list)))
sem_Gens_Cons :: (T_Gen) ->
                 (T_Gens) ->
                 (T_Gens)
sem_Gens_Cons (_hd) (_tl) (_lhs_cDef) =
    let ( _hd_gen) =
            (_hd (_lhs_cDef))
        ( _tl_list) =
            (_tl (_lhs_cDef))
    in  (_hd_gen : _tl_list)
sem_Gens_Nil :: (T_Gens)
sem_Gens_Nil (_lhs_cDef) =
    let 
    in  ([])
-- Morph -------------------------------------------------------
{-
   inherited attributes:
      cDef                 : Concepts
      gE                   : GenR
      isign                : [(Concept,Concept)]
      mDef                 : Morphisms

   chained attributes:

   synthesised attributes:
      atts                 : [Concept]
      id                   : Bool
      morph                : Morph
      mors                 : Morphisms
      nm                   : String
      pos                  : FilePos
      sErr                 : [String]
      signs                : [(Concept,Concept)]

-}
{-
   local variables for Morph.Id:
      is

-}
{-
   local variables for Morph.Mph:
      ms'
      ms
      is

-}
-- semantic domain
type T_Morph = (Concepts) ->
               (GenR) ->
               ([(Concept,Concept)]) ->
               (Morphisms) ->
               (([Concept]),(Bool),(Morph),(Morphisms),(String),(FilePos),([String]),([(Concept,Concept)]))
-- cata
sem_Morph :: (Morph) ->
             (T_Morph)
sem_Morph ((Id (_pos) (_atts) (_c))) =
    (sem_Morph_Id (_pos) (_atts) ((sem_Concept (_c))))
sem_Morph ((Mph (_nm) (_pos) (_atts) (_sgn) (_m))) =
    (sem_Morph_Mph (_nm) (_pos) (_atts) (_sgn) ((sem_Morphism (_m))))
sem_Morph_Id :: (FilePos) ->
                ([Concept]) ->
                (T_Concept) ->
                (T_Morph)
sem_Morph_Id (_pos) (_atts) (_c) (_lhs_cDef) (_lhs_gE) (_lhs_isign) (_lhs_mDef) =
    let (_is) =
            if null _lhs_isign && null _atts
            then error ("Failure to prevent null @lhs.isign and null @atts in I.")
            else if null _lhs_isign
                 then _atts
                 else [lub _lhs_gE a b|(a,b) <- _lhs_isign, order _lhs_gE a b]
        ( _c_concept,_c_nm) =
            (_c (_lhs_cDef))
    in  (_atts
        ,True
        ,Id _pos _atts (foldr1 (lub _lhs_gE) _is)
        ,[]
        ,"I"
        ,_pos
        ,[ "9 in "++show _pos++"\n   Incompatible identity relation I"++show _atts
         | null _lhs_isign ]++
         [ "10 in "++show _pos++"\n   Incompatible concepts for identity relation I"++show _lhs_isign
         | null _is ]++
         [ "11 in "++show _pos++"\n   Multiple concepts (being "++commaAnd (map show _is)++") would match identity relation I."
         | length _is > 1 ]
        ,[(a,a)|a <- _atts]
        )
sem_Morph_Mph :: (String) ->
                 (FilePos) ->
                 ([Concept]) ->
                 ((Concept,Concept)) ->
                 (T_Morphism) ->
                 (T_Morph)
sem_Morph_Mph (_nm) (_pos) (_atts) (_sgn) (_m) (_lhs_cDef) (_lhs_gE) (_lhs_isign) (_lhs_mDef) =
    let (_is) =
            irredM _lhs_gE [ mor | mor <- _ms'
                           , or[source mor `_lhs_gE` a && target mor `_lhs_gE` b|(a,b) <- _lhs_isign]  ]
        (_ms) =
            [ mor | mor <- _lhs_mDef, name mor == _nm]
        (_ms') =
            if null _atts then _ms else
            [ mor | mor <- _ms, source mor == head _atts, target mor == last _atts]
        ( _m_morphism,_m_nm,_m_sErr) =
            (_m (_lhs_cDef))
    in  (_atts
        ,False
        ,let s   = if null _lhs_isign then error("Empty signature allocation for "++show m++" on "++show _pos++":\n  @lhs.isign="++show _lhs_isign++":\n  @ms="++chain "\n       " (map show _ms)++":\n  @ms'="++chain "\n       " (map show _ms')) else
                   if length _lhs_isign>1 then error("Ambiguous signature allocation for "++show m++" on "++show _pos++":\n  @isign contains"++
                                              concat ["\n  "++show sgn| sgn <- _lhs_isign]) else
                   head _lhs_isign
             m   = if null _is then error("Empty morphism allocation for "++show _nm++" on "++show _pos++":\n  @lhs.isign="++show _lhs_isign++":\n  @ms="++chain "\n       " (map show _ms)++":\n  @ms'="++chain "\n       " (map show _ms')) else
                   if length _is>1 then error("Ambiguous morphism allocation for "++show _nm++" on "++show _pos++":\n   "++
                                              chain "\n   " (map show _is)) else
                   head _is
             sgn =
                   [ (a,b) | (a,b) <- _lhs_isign, a `_lhs_gE` source m && b `_lhs_gE` target m ]
         in Mph _nm _pos _atts s m
        ,_ms'
        ,_nm
        ,_pos
        ,[ "7 in "++show _pos++
           "\n   Relation "++show (Mph _nm _pos _atts (C "" [],C "" []) (Idn (C "" []) posNone))++"\n   has more than two concepts."
         | length _atts >2 ]++
         [ "3 in "++show _pos++
           "\n   Relation " ++ show (Mph _nm _pos _atts (C "" [],C "" []) (Idn (C "" []) posNone)) ++
           " is not defined."
         | _ms'==[]]++
         [ "8 in "++show _pos++"\n   Relation "++ show (Mph _nm _pos _atts (C "" [],C "" []) (Idn (C "" []) posNone)) ++
           " is not declared.\n   @lhs.isign="++show _lhs_isign++
           ",\n   @lhs.signs = "++show[ (source mor,target mor) | mor <- _ms']++
           ",\n    "++
           chain "\n    "
           [ "(a,b)="++show (a,b)++", (a',b')="++show (a',b')++", lubs: ("++ show (lub _lhs_gE a a')++","++show (lub _lhs_gE b b')++")"
           | (a,b)<- _lhs_isign, (a',b')<-[ (source mor,target mor) | mor <- _ms']] ++
           "\n   @ms = "++show _ms
         | null _is && null _lhs_isign ]
        ,if null _atts then [ (source mor,target mor) | mor <- _ms'] else [(head _atts,last _atts)]
        )
-- Morphism ----------------------------------------------------
{-
   inherited attributes:
      cDef                 : Concepts

   chained attributes:

   synthesised attributes:
      morphism             : Morphism
      nm                   : String
      sErr                 : [String]

-}
{-
   local variables for Morphism.Idn:

-}
{-
   local variables for Morphism.Mor:

-}
-- semantic domain
type T_Morphism = (Concepts) ->
                  ((Morphism),(String),([String]))
-- cata
sem_Morphism :: (Morphism) ->
                (T_Morphism)
sem_Morphism ((Idn (_c) (_morPos))) =
    (sem_Morphism_Idn ((sem_Concept (_c))) (_morPos))
sem_Morphism ((Mor (_nm) (_a) (_b) (_props) (_prL) (_prM) (_prR) (_content) (_morPos))) =
    (sem_Morphism_Mor (_nm) ((sem_Concept (_a))) ((sem_Concept (_b))) (_props) (_prL) (_prM) (_prR) (_content) (_morPos))
sem_Morphism_Idn :: (T_Concept) ->
                    (FilePos) ->
                    (T_Morphism)
sem_Morphism_Idn (_c) (_morPos) (_lhs_cDef) =
    let ( _c_concept,_c_nm) =
            (_c (_lhs_cDef))
    in  (Idn (head ([con| con <- _lhs_cDef , _c_nm == name con]++[_c_concept])) _morPos,"I",[])
sem_Morphism_Mor :: (String) ->
                    (T_Concept) ->
                    (T_Concept) ->
                    ([Prop]) ->
                    (String) ->
                    (String) ->
                    (String) ->
                    ([Drecord]) ->
                    (FilePos) ->
                    (T_Morphism)
sem_Morphism_Mor (_nm) (_a) (_b) (_props) (_prL) (_prM) (_prR) (_content) (_morPos) (_lhs_cDef) =
    let ( _a_concept,_a_nm) =
            (_a (_lhs_cDef))
        ( _b_concept,_b_nm) =
            (_b (_lhs_cDef))
    in  (Mor _nm (C _a_nm []) (C _b_nm []) _props _prL _prM _prR _content _morPos
        ,_nm
        ,if _a_nm == _b_nm then [] else
         let ps = _props `isc` [Trn,Rfx,Sym,Asy] in
         if null ps then []
         else ["6 in "++show _morPos++"\n   Heterogeneous relation "++
               _nm++"["++ _a_nm ++"*"++ _b_nm ++
               "]\n   may not be declared "++commaAnd [pMeaning p| p<-ps]++
               ".\n   (This relation is heterogeneous because "++ _a_nm ++" and "++ _b_nm ++
               "\n   are different concepts)."]
        )
-- Morphisms ---------------------------------------------------
{-
   inherited attributes:
      cDef                 : Concepts

   chained attributes:

   synthesised attributes:
      list                 : Morphisms
      sErr                 : [String]

-}
{-
   local variables for Morphisms.Cons:

-}
{-
   local variables for Morphisms.Nil:

-}
-- semantic domain
type T_Morphisms = (Concepts) ->
                   ((Morphisms),([String]))
-- cata
sem_Morphisms :: (Morphisms) ->
                 (T_Morphisms)
sem_Morphisms (list) =
    (foldr (sem_Morphisms_Cons) (sem_Morphisms_Nil) ((map sem_Morphism list)))
sem_Morphisms_Cons :: (T_Morphism) ->
                      (T_Morphisms) ->
                      (T_Morphisms)
sem_Morphisms_Cons (_hd) (_tl) (_lhs_cDef) =
    let ( _hd_morphism,_hd_nm,_hd_sErr) =
            (_hd (_lhs_cDef))
        ( _tl_list,_tl_sErr) =
            (_tl (_lhs_cDef))
    in  ([m| m<-[ _hd_morphism], not (isIdent m)] ++ _tl_list,_hd_sErr ++ _tl_sErr)
sem_Morphisms_Nil :: (T_Morphisms)
sem_Morphisms_Nil (_lhs_cDef) =
    let 
    in  ([],[])
-- Patterns ----------------------------------------------------
{-
   inherited attributes:
      cDef                 : Concepts
      gE                   : GenR
      mDef                 : Morphisms

   chained attributes:
      nr                   : Int

   synthesised attributes:
      conDefs              : [ConceptDef]
      mGen                 : Gens
      morphisms            : Morphisms
      patterns             : Patterns
      sErr                 : [String]

-}
{-
   local variables for Patterns.Cons:

-}
{-
   local variables for Patterns.Nil:

-}
-- semantic domain
type T_Patterns = (Concepts) ->
                  (GenR) ->
                  (Morphisms) ->
                  (Int) ->
                  (([ConceptDef]),(Gens),(Morphisms),(Int),(Patterns),([String]))
-- cata
sem_Patterns :: (Patterns) ->
                (T_Patterns)
sem_Patterns (list) =
    (foldr (sem_Patterns_Cons) (sem_Patterns_Nil) ((map sem_Spec list)))
sem_Patterns_Cons :: (T_Spec) ->
                     (T_Patterns) ->
                     (T_Patterns)
sem_Patterns_Cons (_hd) (_tl) (_lhs_cDef) (_lhs_gE) (_lhs_mDef) (_lhs_nr) =
    let ( _hd_conDefs,_hd_mGen,_hd_morphisms,_hd_nr,_hd_pattern,_hd_sErr) =
            (_hd (_lhs_cDef) (_lhs_gE) (_lhs_mDef) (_lhs_nr))
        ( _tl_conDefs,_tl_mGen,_tl_morphisms,_tl_nr,_tl_patterns,_tl_sErr) =
            (_tl (_lhs_cDef) (_lhs_gE) (_lhs_mDef) (_hd_nr))
    in  (_hd_conDefs ++ _tl_conDefs,_hd_mGen ++ _tl_mGen,_hd_morphisms ++ _tl_morphisms,_tl_nr,_hd_pattern : _tl_patterns,_hd_sErr ++ _tl_sErr)
sem_Patterns_Nil :: (T_Patterns)
sem_Patterns_Nil (_lhs_cDef) (_lhs_gE) (_lhs_mDef) (_lhs_nr) =
    let 
    in  ([],[],[],_lhs_nr,[],[])
-- Prop --------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Prop.Asy:

-}
{-
   local variables for Prop.Inj:

-}
{-
   local variables for Prop.Sur:

-}
{-
   local variables for Prop.Sym:

-}
{-
   local variables for Prop.Tot:

-}
{-
   local variables for Prop.Trn:

-}
{-
   local variables for Prop.Uni:

-}
-- semantic domain
type T_Prop = ()
-- cata
sem_Prop :: (Prop) ->
            (T_Prop)
sem_Prop ((Asy )) =
    (sem_Prop_Asy )
sem_Prop ((Inj )) =
    (sem_Prop_Inj )
sem_Prop ((Sur )) =
    (sem_Prop_Sur )
sem_Prop ((Sym )) =
    (sem_Prop_Sym )
sem_Prop ((Tot )) =
    (sem_Prop_Tot )
sem_Prop ((Trn )) =
    (sem_Prop_Trn )
sem_Prop ((Uni )) =
    (sem_Prop_Uni )
sem_Prop_Asy :: (T_Prop)
sem_Prop_Asy  =
    let 
    in  ()
sem_Prop_Inj :: (T_Prop)
sem_Prop_Inj  =
    let 
    in  ()
sem_Prop_Sur :: (T_Prop)
sem_Prop_Sur  =
    let 
    in  ()
sem_Prop_Sym :: (T_Prop)
sem_Prop_Sym  =
    let 
    in  ()
sem_Prop_Tot :: (T_Prop)
sem_Prop_Tot  =
    let 
    in  ()
sem_Prop_Trn :: (T_Prop)
sem_Prop_Trn  =
    let 
    in  ()
sem_Prop_Uni :: (T_Prop)
sem_Prop_Uni  =
    let 
    in  ()
-- Rule --------------------------------------------------------
{-
   inherited attributes:
      cDef                 : Concepts
      gE                   : GenR
      mDef                 : Morphisms
      nr                   : Int

   chained attributes:

   synthesised attributes:
      mGen                 : Gens
      rules                : Rules
      sErr                 : [String]

-}
{-
   local variables for Rule.Dc:
      r
      is
      s

-}
{-
   local variables for Rule.Gc:
      esign
      ms
      is
      s

-}
{-
   local variables for Rule.Hc:
      r
      is
      s

-}
-- semantic domain
type T_Rule = (Concepts) ->
              (GenR) ->
              (Morphisms) ->
              (Int) ->
              ((Gens),(Rules),([String]))
-- cata
sem_Rule :: (Rule) ->
            (T_Rule)
sem_Rule ((Dc (_defd) (_rulePos) (_expr) (_expl) (_sgn) (_nr))) =
    (sem_Rule_Dc ((sem_Morph (_defd))) (_rulePos) ((sem_Factor (_expr))) (_expl) (_sgn) (_nr))
sem_Rule ((Gc (_gluePos) (_m) (_expr) (_sgn) (_nr))) =
    (sem_Rule_Gc (_gluePos) ((sem_Morph (_m))) ((sem_Factor (_expr))) (_sgn) (_nr))
sem_Rule ((Hc (_antc) (_rulePos) (_cons) (_expl) (_sgn) (_nr))) =
    (sem_Rule_Hc ((sem_Factor (_antc))) (_rulePos) ((sem_Factor (_cons))) (_expl) (_sgn) (_nr))
sem_Rule_Dc :: (T_Morph) ->
               (FilePos) ->
               (T_Factor) ->
               (String) ->
               ((Concept,Concept)) ->
               (Int) ->
               (T_Rule)
sem_Rule_Dc (_defd) (_rulePos) (_expr) (_expl) (_sgn) (_nr) (_lhs_cDef) (_lhs_gE) (_lhs_mDef) (_lhs_nr) =
    let (_s) =
            irred _lhs_gE
             [ (lub _lhs_gE a a',lub _lhs_gE b b')
             | (a,b) <- _expr_signs, (a',b') <- _defd_signs
             , order _lhs_gE a' a && order _lhs_gE b' b]
        (_is) =
            if null _defd_signs
            then if null _expr_signs
                 then error ("in "++show _rulePos++"(fatal error)")
                 else _expr_signs
            else if null _expr_signs
                 then _defd_signs
                 else _s
        (_r) =
            Dc _defd_morph _rulePos _expr_factor _expl (if null _is then error("null @is on "++show _rulePos++"\n@defd.morph = "++show _defd_morph++"\n@defd.signs = "++show _defd_signs++"\n@expr.factor = "++show _expr_factor++"\n@expr.signs = "++show _expr_signs) else head _is) _lhs_nr
        ( _defd_atts,_defd_id,_defd_morph,_defd_mors,_defd_nm,_defd_pos,_defd_sErr,_defd_signs) =
            (_defd (_lhs_cDef) (_lhs_gE) (if null _is then _defd_signs else _is) (_lhs_mDef))
        ( _expr_factor,_expr_sErr,_expr_signs) =
            (_expr (_lhs_cDef) (_lhs_gE) (if null _is then _expr_signs else _is) (_lhs_mDef))
    in  ([]
        ,[ _r ]
        ,let sh (Mph nm pos [] _ _) sgns = nm++" :: "++show sgns
             sh (Mph nm pos as _ _) sgns = nm++show as
             sh (Id pos [] _) sgns = "I"++" :: "++show sgns
             sh (Id pos cs _) sgns = "I"++show cs
         in take 1
          ([ "0 in "++show _rulePos++"\n   Meaningless rule."
           | null _defd_signs && null _expr_signs ]++
           [ "1 in "++show _rulePos++"\n   Mismatch in rule:\n   "++
             sh _defd_morph _defd_signs ++ " does not match\n   "++
             show _expr_factor++ " :: "++show _expr_signs
           | null _is && not (null _defd_signs) && not (null _expr_signs)]++
           _defd_sErr ++ _expr_sErr ++
           [ "2 in "++show _rulePos++"\n   Ambiguous signatures: "++commaAnd (map showSign _is)++
             "\n   in right hand side:  "++ show _expr_factor++
             "\n   and left hand side:  "++ show _defd_morph
           | length _is>1])
        )
sem_Rule_Gc :: (FilePos) ->
               (T_Morph) ->
               (T_Factor) ->
               ((Concept,Concept)) ->
               (Int) ->
               (T_Rule)
sem_Rule_Gc (_gluePos) (_m) (_expr) (_sgn) (_nr) (_lhs_cDef) (_lhs_gE) (_lhs_mDef) (_lhs_nr) =
    let (_s) =
            irred _lhs_gE
             [ (lub _lhs_gE a a',lub _lhs_gE b b')
             | (a,b) <- _expr_signs, (a',b') <- _m_signs
             , order _lhs_gE a' a && order _lhs_gE b' b]
        (_is) =
            if null _m_signs
            then if null _expr_signs
                 then error ("in "++show _gluePos++"(fatal error)")
                 else _expr_signs
            else if null _expr_signs
                 then _m_signs
                 else _s
        (_ms) =
            if null _expr_signs then _m_mors else
            [ m| m <- _m_mors
               , or[s `_lhs_gE` source m && t `_lhs_gE` target m| (s,t) <- _expr_signs ]]
        (_esign) =
            irred _lhs_gE _expr_signs
        ( _m_atts,_m_id,_m_morph,_m_mors,_m_nm,_m_pos,_m_sErr,_m_signs) =
            (_m (_lhs_cDef) (_lhs_gE) (irred _lhs_gE [(source m,target m)| m <- _ms]) (_lhs_mDef))
        ( _expr_factor,_expr_sErr,_expr_signs) =
            (_expr (_lhs_cDef) (_lhs_gE) (if null _is then _expr_signs else _is) (_lhs_mDef))
    in  (clearG [g| (d,c) <- _expr_signs, m <- _m_mors, g<-[G d (source m), G c (target m)]]
        ,[Gc _gluePos (Mph _m_nm _m_pos _m_atts sgn m) (_expr_factor) sgn 0
         | (d,c) <- _expr_signs, m <- _m_mors
         , d `_lhs_gE` source m, c `_lhs_gE` target m
         , sgn<-[if null _m_atts then (source m,target m) else (head _m_atts,last _m_atts)]]
        ,let sh (Mph nm pos [] _ _) [] = nm
             sh (Mph nm pos [] _ _) sgns = nm++" :: "++show sgns
             sh (Mph nm pos as _ _) sgns = nm++show as
             sh (Id pos [] _) sgns = "I"++" :: "++show sgns
             sh (Id pos cs _) sgns = "I"++show cs
         in take 1
          ([ "13 in "++show _gluePos++
             "\n   I not allowed as left hand side of GLUE"
           | null _ms && _m_id] ++
           ["14 in "++show _gluePos++"\n   I not allowed as right hand side of GLUE"| null _expr_signs]++
           _m_sErr ++ _expr_sErr ++
           ["12 in "++show _gluePos++"\n   Mismatch in GLUE:\n   "++ _m_nm++" :: "++
                 show _m_signs++
                 "  does not match\n   "++
                 show _expr_factor++" :: "++show _expr_signs
           | null _s && not (null _m_signs && null _expr_signs) ]
           )
        )
sem_Rule_Hc :: (T_Factor) ->
               (FilePos) ->
               (T_Factor) ->
               (String) ->
               ((Concept,Concept)) ->
               (Int) ->
               (T_Rule)
sem_Rule_Hc (_antc) (_rulePos) (_cons) (_expl) (_sgn) (_nr) (_lhs_cDef) (_lhs_gE) (_lhs_mDef) (_lhs_nr) =
    let (_s) =
            irred _lhs_gE
             [ (lub _lhs_gE a a',lub _lhs_gE b b')
             | (a,b) <- _cons_signs, (a',b') <- _antc_signs
             , order _lhs_gE a' a && order _lhs_gE b' b]
        (_is) =
            if null _antc_signs
            then if null _cons_signs
                 then error ("in "++show _rulePos++"(fatal error)")
                 else _cons_signs
            else if null _cons_signs
                 then _antc_signs
                 else _s
        (_r) =
            Hc _antc_factor _rulePos _cons_factor _expl (if null _is then error("null @is on "++show _rulePos++"\n@antc.factor = "++show _antc_factor++"\n@antc.signs = "++show _antc_signs++"\n@cons.factor = "++show _cons_factor++"\n@cons.signs = "++show _cons_signs) else head _is) _lhs_nr
        ( _antc_factor,_antc_sErr,_antc_signs) =
            (_antc (_lhs_cDef) (_lhs_gE) (if null _is then _antc_signs else _is) (_lhs_mDef))
        ( _cons_factor,_cons_sErr,_cons_signs) =
            (_cons (_lhs_cDef) (_lhs_gE) (if null _is then _cons_signs else _is) (_lhs_mDef))
    in  ([]
        ,[ _r ]
        ,take 1
          ([ "0 in "++show _rulePos++"\n   Meaningless rule."
           | null _antc_signs && null _cons_signs ]++
           [ "1 in "++show _rulePos++"\n   Mismatch in rule:\n   "++
             show _antc_factor++ " :: "++show _antc_signs ++ " does not match\n   "++
             show _cons_factor++ " :: "++show _cons_signs
           | null _is && not (null _antc_signs) && not (null _cons_signs)]++
           _antc_sErr ++ _cons_sErr ++
           [ "2 in "++show _rulePos++"\n   Ambiguous signatures: "++commaAnd (map showSign _is)++
             "\n   in right hand side:  "++ show _cons_factor++
             "\n   and left hand side:  "++ show _antc_factor
           | length _is>1])
        )
-- Rules -------------------------------------------------------
{-
   inherited attributes:
      cDef                 : Concepts
      gE                   : GenR
      mDef                 : Morphisms

   chained attributes:
      nr                   : Int

   synthesised attributes:
      mGen                 : Gens
      rules                : Rules
      sErr                 : [String]

-}
{-
   local variables for Rules.Cons:

-}
{-
   local variables for Rules.Nil:

-}
-- semantic domain
type T_Rules = (Concepts) ->
               (GenR) ->
               (Morphisms) ->
               (Int) ->
               ((Gens),(Int),(Rules),([String]))
-- cata
sem_Rules :: (Rules) ->
             (T_Rules)
sem_Rules (list) =
    (foldr (sem_Rules_Cons) (sem_Rules_Nil) ((map sem_Rule list)))
sem_Rules_Cons :: (T_Rule) ->
                  (T_Rules) ->
                  (T_Rules)
sem_Rules_Cons (_hd) (_tl) (_lhs_cDef) (_lhs_gE) (_lhs_mDef) (_lhs_nr) =
    let ( _hd_mGen,_hd_rules,_hd_sErr) =
            (_hd (_lhs_cDef) (_lhs_gE) (_lhs_mDef) (_lhs_nr))
        ( _tl_mGen,_tl_nr,_tl_rules,_tl_sErr) =
            (_tl (_lhs_cDef) (_lhs_gE) (_lhs_mDef) (_lhs_nr+1))
    in  (_hd_mGen ++ _tl_mGen,_tl_nr,_hd_rules ++ _tl_rules,_hd_sErr ++ _tl_sErr)
sem_Rules_Nil :: (T_Rules)
sem_Rules_Nil (_lhs_cDef) (_lhs_gE) (_lhs_mDef) (_lhs_nr) =
    let 
    in  ([],_lhs_nr,[],[])
-- Spec --------------------------------------------------------
{-
   inherited attributes:
      cDef                 : Concepts
      gE                   : GenR
      mDef                 : Morphisms

   chained attributes:
      nr                   : Int

   synthesised attributes:
      conDefs              : [ConceptDef]
      mGen                 : Gens
      morphisms            : Morphisms
      pattern              : Spec
      sErr                 : [String]

-}
{-
   local variables for Spec.Pat:

-}
-- semantic domain
type T_Spec = (Concepts) ->
              (GenR) ->
              (Morphisms) ->
              (Int) ->
              (([ConceptDef]),(Gens),(Morphisms),(Int),(Spec),([String]))
-- cata
sem_Spec :: (Spec) ->
            (T_Spec)
sem_Spec ((Pat (_nm) (_rules) (_gen) (_pms) (_cs))) =
    (sem_Spec_Pat (_nm) ((sem_Rules (_rules))) ((sem_Gens (_gen))) ((sem_Morphisms (_pms))) ((sem_ConceptDefs (_cs))))
sem_Spec_Pat :: (String) ->
                (T_Rules) ->
                (T_Gens) ->
                (T_Morphisms) ->
                (T_ConceptDefs) ->
                (T_Spec)
sem_Spec_Pat (_nm) (_rules) (_gen) (_pms) (_cs) (_lhs_cDef) (_lhs_gE) (_lhs_mDef) (_lhs_nr) =
    let ( _rules_mGen,_rules_nr,_rules_rules,_rules_sErr) =
            (_rules (_lhs_cDef) (_lhs_gE) (_lhs_mDef) (_lhs_nr))
        ( _gen_list) =
            (_gen (_lhs_cDef))
        ( _pms_list,_pms_sErr) =
            (_pms (_lhs_cDef))
        ( _cs_list) =
            (_cs )
    in  (_cs_list,clearG (_rules_mGen ++ _gen_list),_pms_list,_rules_nr,Pat _nm _rules_rules _gen_list _pms_list _cs_list,_rules_sErr ++ _pms_sErr)
-- Term --------------------------------------------------------
{-
   inherited attributes:
      cDef                 : Concepts
      gE                   : GenR
      isign                : [(Concept,Concept)]
      mDef                 : Morphisms

   chained attributes:

   synthesised attributes:
      sErr                 : [String]
      signs                : [(Concept,Concept)]
      term                 : Term

-}
{-
   local variables for Term.Tc:

-}
{-
   local variables for Term.Tf:

-}
{-
   local variables for Term.Tm:

-}
-- semantic domain
type T_Term = (Concepts) ->
              (GenR) ->
              ([(Concept,Concept)]) ->
              (Morphisms) ->
              (([String]),([(Concept,Concept)]),(Term))
-- cata
sem_Term :: (Term) ->
            (T_Term)
sem_Term ((Tc (_c) (_sgn))) =
    (sem_Term_Tc ((sem_Factor (_c))) (_sgn))
sem_Term ((Tf (_f) (_sgn))) =
    (sem_Term_Tf ((sem_Morph (_f))) (_sgn))
sem_Term ((Tm (_m) (_sgn))) =
    (sem_Term_Tm ((sem_Morph (_m))) (_sgn))
sem_Term_Tc :: (T_Factor) ->
               ((Concept,Concept)) ->
               (T_Term)
sem_Term_Tc (_c) (_sgn) (_lhs_cDef) (_lhs_gE) (_lhs_isign) (_lhs_mDef) =
    let ( _c_factor,_c_sErr,_c_signs) =
            (_c (_lhs_cDef) (_lhs_gE) (_lhs_isign) (_lhs_mDef))
    in  (_c_sErr,_c_signs,Tc _c_factor (source _c_factor, target _c_factor))
sem_Term_Tf :: (T_Morph) ->
               ((Concept,Concept)) ->
               (T_Term)
sem_Term_Tf (_f) (_sgn) (_lhs_cDef) (_lhs_gE) (_lhs_isign) (_lhs_mDef) =
    let ( _f_atts,_f_id,_f_morph,_f_mors,_f_nm,_f_pos,_f_sErr,_f_signs) =
            (_f (_lhs_cDef) (_lhs_gE) ([ (b,a)| (a,b) <- _lhs_isign]) (_lhs_mDef))
    in  (_f_sErr,[ (b,a)| (a,b) <- _f_signs],Tf _f_morph (target _f_morph, source _f_morph))
sem_Term_Tm :: (T_Morph) ->
               ((Concept,Concept)) ->
               (T_Term)
sem_Term_Tm (_m) (_sgn) (_lhs_cDef) (_lhs_gE) (_lhs_isign) (_lhs_mDef) =
    let ( _m_atts,_m_id,_m_morph,_m_mors,_m_nm,_m_pos,_m_sErr,_m_signs) =
            (_m (_lhs_cDef) (_lhs_gE) (_lhs_isign) (_lhs_mDef))
    in  (_m_sErr,_m_signs,Tm _m_morph (source _m_morph, target _m_morph))
-- Terms -------------------------------------------------------
{-
   inherited attributes:
      cDef                 : Concepts
      gE                   : GenR
      isign                : [(Concept,Concept)]
      mDef                 : Morphisms

   chained attributes:

   synthesised attributes:
      list                 : Terms
      sErr                 : [String]
      signs                : [(Concept,Concept)]

-}
{-
   local variables for Terms.Cons:
      tripls
      s

-}
{-
   local variables for Terms.Nil:

-}
-- semantic domain
type T_Terms = (Concepts) ->
               (GenR) ->
               ([(Concept,Concept)]) ->
               (Morphisms) ->
               ((Terms),([String]),([(Concept,Concept)]))
-- cata
sem_Terms :: (Terms) ->
             (T_Terms)
sem_Terms (list) =
    (foldr (sem_Terms_Cons) (sem_Terms_Nil) ((map sem_Term list)))
sem_Terms_Cons :: (T_Term) ->
                  (T_Terms) ->
                  (T_Terms)
sem_Terms_Cons (_hd) (_tl) (_lhs_cDef) (_lhs_gE) (_lhs_isign) (_lhs_mDef) =
    let (_s) =
            if null _tl_signs
            then if null _hd_signs
                 then []
                 else _hd_signs
            else if null _hd_signs
                 then _tl_signs
                 else rd [(a,b)| (a,i,b) <- _tripls    ]
        (_tripls) =
            rd [(a,lub _lhs_gE b a',b')| (a,b)<- _hd_signs, (a',b')<- _tl_signs, order _lhs_gE b a']
        ( _hd_sErr,_hd_signs,_hd_term) =
            (_hd (_lhs_cDef)
                 (_lhs_gE)
                 (if null _tl_list  then _lhs_isign else
                  if null _tl_signs then _lhs_isign else
                  if null _hd_signs then irred _lhs_gE [(d,i)| (i,b) <- _tl_signs,     (d,c) <- _lhs_isign] else
                                         irred _lhs_gE [(d,i)| (a,i,b) <- _tripls    , (d,c) <- _lhs_isign, a `_lhs_gE` d && b `_lhs_gE` c])
                 (_lhs_mDef))
        ( _tl_list,_tl_sErr,_tl_signs) =
            (_tl (_lhs_cDef)
                 (_lhs_gE)
                 (if null _tl_list                    then [error "something wrong"] else
                  if null _hd_signs then _lhs_isign else
                  if null _tl_signs then irred _lhs_gE [(i,c)| (a,i)   <- _hd_signs,   (d,c) <- _lhs_isign] else
                                         irred _lhs_gE [(i,c)| (a,i,b) <- _tripls    , (d,c) <- _lhs_isign, a `_lhs_gE` d && b `_lhs_gE` c])
                 (_lhs_mDef))
    in  (_hd_term : _tl_list
        ,[ "5 in "++show (pos (head _tl_list))++"\n   Type error in composing\n   "++name _hd_term++show _hd_signs++
           " with\n   "++show (F _tl_list (C "" [],C "" []))++show _tl_signs
         | not (null _tl_list)
         , not (null _hd_signs) && not (null _tl_signs) && null _s
         ]++ _hd_sErr ++ _tl_sErr
        ,if null _tl_list then _hd_signs else _s
        )
sem_Terms_Nil :: (T_Terms)
sem_Terms_Nil (_lhs_cDef) (_lhs_gE) (_lhs_isign) (_lhs_mDef) =
    let 
    in  ([],[],[])

