 ::Interface*Actueel/Vervallen[UNI]
  = [ ("1","A")
    ; ("10","A")
    ; ("11","A")
    ; ("12","A")
    ; ("13","A")
    ; ("14","A")
    ; ("15","V")
    ; ("16","V")
    ; ("17","A")
    ; ("18","A")
    ; ("19","V")
    ; ("2","A")
    ; ("20","A")
    ; ("21","A")
    ; ("22","A")
    ; ("23","A")
    ; ("24","A")
    ; ("25","A")
    ; ("26","A")
    ; ("27","A")
    ; ("28","A")
    ; ("29","A")
    ; ("3","A")
    ; ("30","A")
    ; ("31","A")
    ; ("32","A")
    ; ("33","A")
    ; ("34","A")
    ; ("35","A")
    ; ("36","A")
    ; ("37","A")
    ; ("38","A")
    ; ("39","A")
    ; ("4","A")
    ; ("40","A")
    ; ("41","A")
    ; ("42","A")
    ; ("43","A")
    ; ("44","A")
    ; ("45","A")
    ; ("46","A")
    ; ("47","A")
    ; ("48","A")
    ; ("49","A")
    ; ("5","V")
    ; ("50","A")
    ; ("51","A")
    ; ("52","A")
    ; ("53","A")
    ; ("54","A")
    ; ("55","A")
    ; ("56","A")
    ; ("57","A")
    ; ("58","A")
    ; ("59","A")
    ; ("6","A")
    ; ("60","A")
    ; ("61","A")
    ; ("62","A")
    ; ("63","A")
    ; ("64","A")
    ; ("65","A")
    ; ("66","A")
    ; ("67","A")
    ; ("68","A")
    ; ("69","A")
    ; ("7","A")
    ; ("70","A")
    ; ("71","A")
    ; ("72","A")
    ; ("73","A")
    ; ("74","A")
    ; ("75","A")
    ; ("76","A")
    ; ("77","A")
    ; ("8","A")
    ; ("9","A")
    ].

 ::Interface*Aard vd data in de uitwisseling[UNI]
  = [ ("1","Image van document")
    ; ("10","Starten van een transactie")
    ; ("11","Teruggeven resultaat transactie")
    ; ("12","Starten van systeem TRAVON voor volmachtschade")
    ; ("13","Teruggeven resultaat TRAVON verwerking")
    ; ("14","Aanbieding transactie ontvangen via MP")
    ; ("15","Aansluiting TP-applicaties")
    ; ("16","?")
    ; ("17","Bericht ontvangen via MP tbv DL")
    ; ("18","Opvragen voertuiggegevens")
    ; ("19","?")
    ; ("2","Event voor proc. Mngr")
    ; ("20","Request of mutatie te verwerken door IDIT")
    ; ("21","Opvraging KvK inschrijving")
    ; ("22","Opvragen voertuiggegevens")
    ; ("23","Controle op voorkomen in FISH\nRaadplegen registratie in FISH\nMelding schade/fraude aan FISH")
    ; ("24","Muteren XE-data")
    ; ("24","Muteren contract")
    ; ("24","Muteren relatie")
    ; ("24","Opvoeren contract")
    ; ("24","Opvoeren relatie")
    ; ("24","Selecteren relatie")
    ; ("24","Zoeken relatie ")
    ; ("25","Aanbieden gegevens uit Acceptatie Collectief\nMelding langdurig verzuim")
    ; ("26","Aan- en afmelding verzekering van voertuig")
    ; ("27","Aanvragen van expertise")
    ; ("28","Reactie en berichten aan beursmakelaar")
    ; ("29","Reactie op GIM aanvragen")
    ; ("3","Rdplg polisinfo Inkomen\nMelding van mutatie")
    ; ("30","Financi\235le feiten gemeld door beursmakelaar")
    ; ("31","Beschikking UWV met (herziene) AO-%")
    ; ("32","Ziekteverzuimopgaves")
    ; ("33","Personeels- en salarismutaties")
    ; ("34","Raadplegen of registreren contactmomenten")
    ; ("35","Aanbieden financi\235le en polisfeiten voor batch-gewijze verwerking")
    ; ("36","Maandafslag van letsel claimbehandeling naar Delfi")
    ; ("37","Status van een claim")
    ; ("38","Mutatie van postcodetabel, regioindeling, e.d.")
    ; ("39","Mutatie van tussenpersoon gegevens op RC-niveau")
    ; ("39","Mutatie van tussenpersoon gegevens op TA-niveau")
    ; ("4","Meldingen en requests van beursmakelaars")
    ; ("40","Mutatie van relatiegegevens")
    ; ("41","Financi\235le feiten voor AP/AR administratie")
    ; ("42","Journaalregels voor grootboek")
    ; ("43","Financi\235le feiten voor schadeuitkeringen")
    ; ("44","Gegevens over uitbetaalde kosten")
    ; ("45","Schadereserveringen")
    ; ("46","Alle transacties")
    ; ("47","Gegevens over verrichte boekingen")
    ; ("48","Wijziging van incasso-wijze voor boeking")
    ; ("49","Bericht voor POR/ADN")
    ; ("5","Ontvangst GIM aanvragen")
    ; ("50","Incassowijze voor polis")
    ; ("51","Output berichten voor OMA")
    ; ("52","Electronisch bericht te verspreiden door ABZ")
    ; ("53","Raadpleging of premie is betaald op datum")
    ; ("54","Wijziging van incasso-wijze voor boeking")
    ; ("55","Incassowijze voor polis")
    ; ("56","Incassowijze voor polis")
    ; ("57","?")
    ; ("58","Opgemaakt document te verspreiden door ABZ")
    ; ("59","Opgemaakt document te verspreiden door MP")
    ; ("6","ADN-aanvragen")
    ; ("60","Opgemaakt document vast te leggen in CM")
    ; ("61","Aanroep voor interactieve opmaak van document")
    ; ("62","Opgemaakt document vast te leggen in CM")
    ; ("63","Aanvraag voor mutatie vanuit applicatie van ATP")
    ; ("64","Aanbieden van resultaat van transactie in GIM formaat")
    ; ("65","Alle acceptatie mutaties")
    ; ("66","Ophalen beschikbare werkpakketten")
    ; ("67","Starten transactie voor geselecteerd werkpakket")
    ; ("68","Aanbieding transactie ontvangen via BETA")
    ; ("69","Opgemaakte output aanbieden aan BETA")
    ; ("7","Aanvraag van klantprofiel")
    ; ("70","Gestructureerd bericht aanbieden aan BETA")
    ; ("71","Teruggeven resultaat verwerking aan MP")
    ; ("72","Terugmelden resultaat transactie aan Desktop")
    ; ("73","Melding bijzonderheden in schadegeval tbv schadelastbeperking")
    ; ("74","Alle schadebehandelings mutaties")
    ; ("75","Mutatie op relatie-gegevens te beoordelen door acceptant")
    ; ("76","Aanvragen voor offerte voor inkomens producten")
    ; ("77","Aanvraag voor toezending ziekteverzuim opgaves")
    ; ("8","Raadplegen klantprofiel")
    ; ("9","Raadplegen electronisch dossier")
    ].

 ::Interface*Requester[UNI]
  = [ ("1","ScanStraat")
    ; ("10","Proces Management")
    ; ("11","IDIT")
    ; ("12","Proces Management")
    ; ("13","TRAVON")
    ; ("14","Meeting Point Trans-actie Management")
    ; ("15","Derden applicaties")
    ; ("16","Meeting Point Trans-actie Management")
    ; ("17","Meeting Point FrontEnd")
    ; ("18","Meeting Point FrontEnd")
    ; ("19","Meeting Point FrontEnd")
    ; ("2","ScanStraat")
    ; ("20","Meeting Point Trans-actie Management")
    ; ("21","IDIT")
    ; ("22","IDIT")
    ; ("24","IDIT")
    ; ("26","IDIT")
    ; ("27","IDIT")
    ; ("28","IDIT")
    ; ("29","IDIT")
    ; ("30","BCS")
    ; ("31","UWV")
    ; ("32","BOA ARBO")
    ; ("33","WN-bestand")
    ; ("34","IDIT")
    ; ("35","IDIT")
    ; ("36","FELET")
    ; ("37","FELET")
    ; ("38","Postcode Tabel")
    ; ("39","Cetis")
    ; ("4","E-ABS")
    ; ("40","Cervis")
    ; ("41","Interface Ontkoppeling")
    ; ("42","Interface Ontkoppeling")
    ; ("43","Interface Ontkoppeling")
    ; ("44","Interface Ontkoppeling")
    ; ("45","Interface Ontkoppeling")
    ; ("46","Interface Ontkoppeling")
    ; ("47","Interface Ontkoppeling")
    ; ("48","BKIS")
    ; ("49","Interface Ontkoppeling/IDIT (?)")
    ; ("5","GIM")
    ; ("50","Interface Ontkoppeling")
    ; ("51","Interface Ontkoppeling/IDIT (?)")
    ; ("52","POR/ADN")
    ; ("53","IDIT")
    ; ("54","QSP AR/AP")
    ; ("55","MAREG")
    ; ("56","MAREG")
    ; ("57","Voor Portaal Output")
    ; ("58","DOC1 Output")
    ; ("59","DOC1 Output")
    ; ("6","ADN Transactie Management")
    ; ("60","DOC1 Output")
    ; ("61","IDIT")
    ; ("62","DOC1 Interactive")
    ; ("63","TP Administratie")
    ; ("64","IDIT")
    ; ("65","IDIT")
    ; ("66","MultiFit Desktop")
    ; ("67","MultiFit Desktop")
    ; ("68","BETA (AAB)")
    ; ("69","DOC1 Output")
    ; ("7","Proces Management")
    ; ("70","IDIT")
    ; ("71","Proces Management")
    ; ("72","IDIT")
    ; ("73","VMC")
    ; ("74","IDIT")
    ; ("75","Cervis")
    ; ("76","Personeels Pakket Offertetool")
    ; ("77","IDIT")
    ; ("8","MultiFit Desktop")
    ; ("9","MultiFit Desktop")
    ].

 ::Interface*Provider[UNI]
  = [ ("1","Content Managent")
    ; ("10","IDIT")
    ; ("11","Proces Management")
    ; ("12","TRAVON")
    ; ("13","Proces Management")
    ; ("14","Proces Management")
    ; ("15","Meeting Point Trans-actie Management")
    ; ("16","RDW")
    ; ("17","Meeting Point Trans-actie Management")
    ; ("18","RDC")
    ; ("19","RDW")
    ; ("2","Proces Management")
    ; ("20","IDIT")
    ; ("21","KvK")
    ; ("22","RDC")
    ; ("24","Cervis")
    ; ("26","RDW")
    ; ("27","SEOS")
    ; ("28","E-ABS")
    ; ("29","GIM")
    ; ("30","IDIT")
    ; ("31","IDIT")
    ; ("32","IDIT")
    ; ("33","IDIT")
    ; ("34","Contact Historie")
    ; ("35","Interface Ontkoppeling")
    ; ("36","Interface Ontkoppeling")
    ; ("37","IDIT")
    ; ("38","IDIT")
    ; ("39","IDIT")
    ; ("4","Proces Management")
    ; ("40","IDIT")
    ; ("41","QSP AR/AP")
    ; ("42","QSP GL")
    ; ("43","KAS")
    ; ("44","Kosten RBB")
    ; ("45","SVS")
    ; ("46","Data Ware-House")
    ; ("47","BKIS")
    ; ("48","IDIT")
    ; ("49","POR/ADN")
    ; ("5","Proces Management")
    ; ("50","MAREG")
    ; ("51","Voor Portaal Output")
    ; ("52","ABZ")
    ; ("53","QSP AR/AP")
    ; ("54","BKIS")
    ; ("55","QSP AR/AP")
    ; ("56","Voor Portaal Output")
    ; ("57","DOC1 Output")
    ; ("58","ABZ")
    ; ("59","Meeting Point FrontEnd")
    ; ("6","Proces Management")
    ; ("60","Content Management")
    ; ("61","DOC1 Interactive")
    ; ("62","Content Management")
    ; ("63","Meeting Point FrontEnd")
    ; ("64","Meeting Point Trans-actie Management")
    ; ("65","BAR")
    ; ("66","Proces Management")
    ; ("67","IDIT")
    ; ("68","Proces Management")
    ; ("69","BETA (AAB)")
    ; ("7","Klant Beeld")
    ; ("70","BETA (AAB)")
    ; ("71","Meeting Point Trans-actie Management")
    ; ("72","MultFit Desktop")
    ; ("73","Proces Management")
    ; ("74","SLB")
    ; ("75","Proces Management")
    ; ("76","Proces Management")
    ; ("77","BOA ARBO")
    ; ("8","Klant Beeld")
    ; ("9","Content Management")
    ].

 ::Interface*Direct/ESB[UNI]
  = [ 
    ].

 ::Interface*Aard Interface[UNI]
  = [ ("1","OL")
    ; ("10","OL")
    ; ("11","OL")
    ; ("12","OL")
    ; ("13","OL")
    ; ("14","OL")
    ; ("15","OL")
    ; ("16","OL")
    ; ("17","OL")
    ; ("18","OL")
    ; ("19","OL")
    ; ("2","OL")
    ; ("20","OL")
    ; ("21","OL")
    ; ("22","OL")
    ; ("24","OL")
    ; ("26","OL")
    ; ("27","OL")
    ; ("28","OL")
    ; ("29","OL")
    ; ("30","BT")
    ; ("31","BT")
    ; ("32","BT")
    ; ("33","BT")
    ; ("34","OL")
    ; ("35","OL")
    ; ("36","OL")
    ; ("37","OL")
    ; ("38","BT")
    ; ("39","OL")
    ; ("4","OL")
    ; ("40","OL")
    ; ("41","BT")
    ; ("42","BT")
    ; ("43","BT")
    ; ("44","BT")
    ; ("45","BT")
    ; ("46","OL ?")
    ; ("47","BT")
    ; ("48","?")
    ; ("49","?")
    ; ("5","OL")
    ; ("50","?")
    ; ("51","OL")
    ; ("52","OL")
    ; ("53","OL")
    ; ("54","?")
    ; ("55","?")
    ; ("56","?")
    ; ("57","BT")
    ; ("58","OL")
    ; ("59","OL")
    ; ("6","OL")
    ; ("60","?")
    ; ("61","OL")
    ; ("62","OL")
    ; ("63","OL")
    ; ("64","OL")
    ; ("65","OL")
    ; ("66","OL")
    ; ("67","OL")
    ; ("68","OL")
    ; ("69","OL")
    ; ("7","OL")
    ; ("70","OL")
    ; ("71","OL")
    ; ("72","OL")
    ; ("73","OL")
    ; ("74","OL")
    ; ("75","OL")
    ; ("76","OL")
    ; ("77","OL")
    ; ("8","OL")
    ; ("9","OL")
    ].

 ::Interface*Type communicatie[UNI]
  = [ ("1","FF")
    ; ("10","FF")
    ; ("11","FF")
    ; ("12","FF")
    ; ("13","FF")
    ; ("14","FF")
    ; ("15","RR")
    ; ("16","?")
    ; ("17","FF")
    ; ("17","RR")
    ; ("18","RR")
    ; ("19","?")
    ; ("2","FF")
    ; ("20","RR")
    ; ("21","RR")
    ; ("22","RR")
    ; ("24","RR")
    ; ("26","FF")
    ; ("27","FF")
    ; ("28","FF")
    ; ("29","FF")
    ; ("30","-")
    ; ("31","-")
    ; ("32","-")
    ; ("33","-")
    ; ("34","FF")
    ; ("35","FF")
    ; ("36","?")
    ; ("37","FF")
    ; ("38","-")
    ; ("39","FF")
    ; ("4","FF")
    ; ("40","FF")
    ; ("41","-")
    ; ("42","-")
    ; ("43","-")
    ; ("44","-")
    ; ("45","-")
    ; ("46","-")
    ; ("47","-")
    ; ("5","FF")
    ; ("51","FF")
    ; ("52","FF")
    ; ("53","RR")
    ; ("57","-")
    ; ("58","FF")
    ; ("59","FF")
    ; ("6","FF")
    ; ("61","FF")
    ; ("62","FF")
    ; ("63","FF")
    ; ("64","FF")
    ; ("65","FF")
    ; ("66","RR")
    ; ("67","FF")
    ; ("68","FF")
    ; ("69","FF")
    ; ("7","RR")
    ; ("70","FF")
    ; ("71","FF")
    ; ("72","FF")
    ; ("73","FF")
    ; ("74","FF")
    ; ("75","FF")
    ; ("76","FF")
    ; ("77","FF")
    ; ("8","FF")
    ; ("9","FF")
    ].

 ::Interface*Service[UNI]
  = [ ("24","Muteer_Contract")
    ; ("24","Muteer_Relatie")
    ; ("24","Muteer_XE_Data")
    ; ("24","Opvoer_Contract")
    ; ("24","Opvoer_Relatie")
    ; ("24","Selecteer_Relatie")
    ; ("24","Zoek_Relatie")
    ; ("39","Mutatie_Publicatie_Regeling")
    ; ("39","Mutatie_Publicatie_Vestiging")
    ; ("40","Mutatie_Publicatie_DLRelatie")
    ].
