-- do not edit; automatically generated by UU.AG
module AGtry where

import UU_Scanner
import UU_Pretty
import Auxiliaries
import Classification
import Typology
import CC_aux


mkCtxAG :: [(Context,(Gens,Signatures))] -> String -> Classification (Context,(Gens,Signatures))
mkCtxAG ctxs ctxName
 = if null ctTrees
   then error ("!Error of type 0: unknown context "++ctxName
               ++".\ntesting: length ctxs="++show (length ctxs)
               ++if length ctxs>1
                 then ".\nPick one of "++chain ", " (map (name.fst) (tail ctxs))++" or "++(name.fst.head) ctxs
                 else if null ctxs then "No context available" else ".\nPick "++(name.fst.head) ctxs
              ) else
   let ecl = [head cl|cl<-eqClass (==) (map (name.fst) ctxs), length cl>1] in
   if null ecl then head ctTrees else
   error ("!Error of type 0: multiple contexts carrying the name "++commaAnd ecl++".")
   where
    ctTrees = [t|tree<-trees, t<-locatesF ((==ctxName).name.fst) tree]
-- multiple ctTrees may occur if contexts are used multiply in different ctTrees.
    trees = makeClassificationsF (name.fst) tuples++[Cl s []| s<-singles]
            where tuples = [ ((spc,(mG,mD)),(gen,(mG',mD')))
                           | (spc@(Ctx nm on isa world dc ms cs),(mG,mD))<-ctxs, o<-on
                           , (gen,(mG',mD'))<-ctxs,name gen==o]
                  singles= [ (spc,(mG,mD))
                           | (spc,(mG,mD))<-ctxs, not (name spc `elem` rd [name c|(s,g)<-tuples, (c,m)<-[s,g]])]

llub gE ss ss'
 = if null ss'
   then if null ss
        then []
        else ss
   else if null ss
        then ss'
        else rd [ (if a `gE` a' then a' else a, if b `gE` b' then b' else b)
                | (a,b)<-ss, (a',b')<-ss'
                , (a `gE` a' || a' `gE` a) && (b `gE` b' || b' `gE` b)
                ]
tlub gE cs [] = []
tlub gE [] cs = []
tlub gE as bs = (map (foldr1 lub) . eqClass order) [lub a b| a<-as, b<-bs, a `order` b]
                where lub (Anything _) b = b
                      lub a (Anything _) = a
                      lub a b = if a `gE` b then b else a
                      order (Anything _) b = True
                      order a (Anything _) = True
                      order a b = a `gE` b || b `gE` a
comp gE [] ts = []
comp gE ss [] = []
comp gE ss ts = [(f a a' b,f b' a' b)|(a,b)<-ss, (a',b')<-ts, a' `gE` b || b `gE` a']
                where f (Anything _) x y | x `gE` y = y
                                         | y `gE` x = x
                      f a _ _ = a
comps gE tss  = if null ss then [] else foldr1 (comp gE) ss
                where ss=[s|s<-tss, not (null s)]
distr (a,b) css ts = if and [length cs<=1|cs<-css]
                     then [specialize (x,y) t| (x,y,t)<-zip3 ([a]++cs) (cs++[b]) ts]
                     else error ("Fatal: ambiguities "++show css)
                     where cs  = [c|[c]<-css]
-- Architecture ------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      cs                   : [Context]
      sErr                 : [String]

-}
{-
   local variables for Architecture.Arch:

-}
-- semantic domain
type T_Architecture = ( ([Context]),([String]))
-- cata
sem_Architecture :: (Architecture) ->
                    (T_Architecture)
sem_Architecture ((Arch (_cs))) =
    (sem_Architecture_Arch ((sem_Contexts (_cs))))
sem_Architecture_Arch :: (T_Contexts) ->
                         (T_Architecture)
sem_Architecture_Arch (cs_) =
    let _lhsOcs :: ([Context])
        _lhsOsErr :: ([String])
        _csIcontexts :: (Contexts)
        _csIover :: ([(Context,(Gens,Signatures))])
        _csIsErr :: ([String])
        _csOctxs :: ([(Context,(Gens,Signatures))])
        ( _csIcontexts,_csIover,_csIsErr) =
            (cs_ (_csOctxs))
        -- "AGtry.ag"(line 71, column 10)
        (_csOctxs@_) =
            _csIover
        -- "AGtry.ag"(line 70, column 10)
        (_lhsOcs@_) =
            _csIcontexts
        -- "AGtry.ag"(line 261, column 10)
        (_lhsOsErr@_) =
            _csIsErr
    in  ( _lhsOcs,_lhsOsErr)
-- Concept -----------------------------------------------------
{-
   inherited attributes:
      gE                   : GenR

   chained attributes:

   synthesised attributes:
      concept              : Concept
      nm                   : String

-}
{-
   local variables for Concept.C:

-}
-- semantic domain
type T_Concept = (GenR) ->
                 ( (Concept),(String))
-- cata
sem_Concept :: (Concept) ->
               (T_Concept)
sem_Concept ((C (_c) (_gE) (_os))) =
    (sem_Concept_C (_c) (_gE) (_os))
sem_Concept_C :: (String) ->
                 (GenR) ->
                 ([String]) ->
                 (T_Concept)
sem_Concept_C (c_) (gE_) (os_) =
    \ _lhsIgE ->
        let _lhsOconcept :: (Concept)
            _lhsOnm :: (String)
            -- "AGtry.ag"(line 434, column 7)
            (_lhsOnm@_) =
                c_
            -- "AGtry.ag"(line 433, column 7)
            (_lhsOconcept@_) =
                C c_ _lhsIgE []
        in  ( _lhsOconcept,_lhsOnm)
-- ConceptDef --------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      c                    : ConceptDef

-}
{-
   local variables for ConceptDef.Cd:

-}
-- semantic domain
type T_ConceptDef = ( (ConceptDef))
-- cata
sem_ConceptDef :: (ConceptDef) ->
                  (T_ConceptDef)
sem_ConceptDef ((Cd (_pos) (_nm) (_def) (_ref))) =
    (sem_ConceptDef_Cd (_pos) (_nm) (_def) (_ref))
sem_ConceptDef_Cd :: (FilePos) ->
                     (String) ->
                     (String) ->
                     (String) ->
                     (T_ConceptDef)
sem_ConceptDef_Cd (pos_) (nm_) (def_) (ref_) =
    let _lhsOc :: (ConceptDef)
        -- "AGtry.ag"(line 438, column 8)
        (_lhsOc@_) =
            Cd pos_ nm_ def_ ref_
    in  ( _lhsOc)
-- ConceptDefs -------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:
      conDefs              : [ConceptDef]

-}
{-
   local variables for ConceptDefs.Cons:

-}
{-
   local variables for ConceptDefs.Nil:

-}
-- semantic domain
type T_ConceptDefs = ( ([ConceptDef]))
-- cata
sem_ConceptDefs :: (ConceptDefs) ->
                   (T_ConceptDefs)
sem_ConceptDefs (list) =
    (foldr (sem_ConceptDefs_Cons) (sem_ConceptDefs_Nil) ((map sem_ConceptDef list)))
sem_ConceptDefs_Cons :: (T_ConceptDef) ->
                        (T_ConceptDefs) ->
                        (T_ConceptDefs)
sem_ConceptDefs_Cons (hd_) (tl_) =
    let _lhsOconDefs :: ([ConceptDef])
        _hdIc :: (ConceptDef)
        _tlIconDefs :: ([ConceptDef])
        ( _hdIc) =
            (hd_ )
        ( _tlIconDefs) =
            (tl_ )
        -- "AGtry.ag"(line 442, column 10)
        (_lhsOconDefs@_) =
            _hdIc : _tlIconDefs
    in  ( _lhsOconDefs)
sem_ConceptDefs_Nil :: (T_ConceptDefs)
sem_ConceptDefs_Nil  =
    let _lhsOconDefs :: ([ConceptDef])
        -- "AGtry.ag"(line 443, column 10)
        (_lhsOconDefs@_) =
            []
    in  ( _lhsOconDefs)
-- Concepts ----------------------------------------------------
{-
   inherited attributes:
      gE                   : GenR

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Concepts.Cons:

-}
{-
   local variables for Concepts.Nil:

-}
-- semantic domain
type T_Concepts = (GenR) ->
                  ( )
-- cata
sem_Concepts :: (Concepts) ->
                (T_Concepts)
sem_Concepts (list) =
    (foldr (sem_Concepts_Cons) (sem_Concepts_Nil) ((map sem_Concept list)))
sem_Concepts_Cons :: (T_Concept) ->
                     (T_Concepts) ->
                     (T_Concepts)
sem_Concepts_Cons (hd_) (tl_) =
    \ _lhsIgE ->
        let _hdIconcept :: (Concept)
            _hdInm :: (String)
            _hdOgE :: (GenR)
            _tlOgE :: (GenR)
            ( _hdIconcept,_hdInm) =
                (hd_ (_hdOgE))
            -- copy rule (down)
            (_hdOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_tlOgE@_) =
                _lhsIgE
        in  ( )
sem_Concepts_Nil :: (T_Concepts)
sem_Concepts_Nil  =
    \ _lhsIgE ->
        let 
        in  ( )
-- Context -----------------------------------------------------
{-
   inherited attributes:
      ctxTree              : Classification (Context,(Gens,Signatures))
      ctxs                 : [(Context,(Gens,Signatures))]

   chained attributes:

   synthesised attributes:
      context              : Context
      over                 : [(Context,(Gens,Signatures))]
      sErr                 : [String]

-}
{-
   local variables for Context.Ctx:
      cD
      genE
      inh
      mGen
      mD

-}
-- semantic domain
type T_Context = (Classification (Context,(Gens,Signatures))) ->
                 ([(Context,(Gens,Signatures))]) ->
                 ( (Context),([(Context,(Gens,Signatures))]),([String]))
-- cata
sem_Context :: (Context) ->
               (T_Context)
sem_Context ((Ctx (_nm) (_on) (_isa) (_world) (_dc) (_ms) (_cs))) =
    (sem_Context_Ctx (_nm) (_on) (_isa) (_world) ((sem_Patterns (_dc))) ((sem_Signatures (_ms))) ((sem_ConceptDefs (_cs))))
sem_Context_Ctx :: (String) ->
                   ([String]) ->
                   (Inheritance Concept) ->
                   ([Classification Context]) ->
                   (T_Patterns) ->
                   (T_Signatures) ->
                   (T_ConceptDefs) ->
                   (T_Context)
sem_Context_Ctx (nm_) (on_) (isa_) (world_) (dc_) (ms_) (cs_) =
    \ _lhsIctxTree
      _lhsIctxs ->
        let _lhsOcontext :: (Context)
            _lhsOover :: ([(Context,(Gens,Signatures))])
            _lhsOsErr :: ([String])
            _dcIconDefs :: ([ConceptDef])
            _dcImGen :: (Gens)
            _dcImorphisms :: ([Morphism])
            _dcInr :: (Int)
            _dcIpatterns :: (Patterns)
            _dcIsErr :: ([String])
            _dcIsignatures :: (Signatures)
            _dcOgE :: (GenR)
            _dcOmDef :: (Signatures)
            _dcOnr :: (Int)
            _msIsErr :: ([String])
            _msIsignatures :: (Signatures)
            _msOgE :: (GenR)
            _csIconDefs :: ([ConceptDef])
            ( _dcIconDefs,_dcImGen,_dcImorphisms,_dcInr,_dcIpatterns,_dcIsErr,_dcIsignatures) =
                (dc_ (_dcOgE) (_dcOmDef) (_dcOnr))
            ( _msIsErr,_msIsignatures) =
                (ms_ (_msOgE))
            ( _csIconDefs) =
                (cs_ )
            -- "AGtry.ag"(line 89, column 9)
            (_lhsOcontext@_) =
                populate _cD (Ctx nm_ on_ _inh [cl|Cl r cls<-[mapCl fst _lhsIctxTree], cl<-cls]
                                  _dcIpatterns _msIsignatures (sort' name (rd (_csIconDefs ++ _dcIconDefs))))
            -- "AGtry.ag"(line 87, column 9)
            (_lhsOover@_) =
                [( populate _cD (Ctx nm_ on_ _inh [] _dcIpatterns _msIsignatures _csIconDefs)
                 , (_dcImGen, _msIsignatures ++ _dcIsignatures))]
            -- "AGtry.ag"(line 86, column 9)
            (_msOgE@_) =
                _genE
            -- "AGtry.ag"(line 85, column 9)
            (_dcOgE@_) =
                _genE
            -- "AGtry.ag"(line 84, column 9)
            (_dcOmDef@_) =
                _mD
            -- "AGtry.ag"(line 83, column 9)
            (_cD@_) =
                makeConceptSpace _dcImorphisms
            -- "AGtry.ag"(line 80, column 9)
            (_genE@_) =
                cmp where cmp (Anything _) b = True
                          cmp a (Anything _) = False
                          cmp a b            = if a==b then True else genEq (typology _inh) a b
            -- "AGtry.ag"(line 79, column 9)
            (_inh@_) =
                Isa [(g,s)|G g s<- _mGen] (concs _mD>-rd [c|G g s<- _mGen, c<-[g,s]])
            -- "AGtry.ag"(line 78, column 9)
            (_mGen@_) =
                (rd.concat) [mG| (ctx,(mG,mD)) <- preCl _lhsIctxTree]
            -- "AGtry.ag"(line 77, column 9)
            (_mD@_) =
                concat[mD| (ctx,(mG,mD)) <- preCl _lhsIctxTree]
            -- "AGtry.ag"(line 266, column 10)
            (_lhsOsErr@_) =
                _dcIsErr
            -- "AGtry.ag"(line 411, column 9)
            (_dcOnr@_) =
                1
        in  ( _lhsOcontext,_lhsOover,_lhsOsErr)
-- Contexts ----------------------------------------------------
{-
   inherited attributes:
      ctxs                 : [(Context,(Gens,Signatures))]

   chained attributes:

   synthesised attributes:
      contexts             : Contexts
      over                 : [(Context,(Gens,Signatures))]
      sErr                 : [String]

-}
{-
   local variables for Contexts.Cons:

-}
{-
   local variables for Contexts.Nil:

-}
-- semantic domain
type T_Contexts = ([(Context,(Gens,Signatures))]) ->
                  ( (Contexts),([(Context,(Gens,Signatures))]),([String]))
-- cata
sem_Contexts :: (Contexts) ->
                (T_Contexts)
sem_Contexts (list) =
    (foldr (sem_Contexts_Cons) (sem_Contexts_Nil) ((map sem_Context list)))
sem_Contexts_Cons :: (T_Context) ->
                     (T_Contexts) ->
                     (T_Contexts)
sem_Contexts_Cons (hd_) (tl_) =
    \ _lhsIctxs ->
        let _lhsOcontexts :: (Contexts)
            _lhsOover :: ([(Context,(Gens,Signatures))])
            _lhsOsErr :: ([String])
            _hdIcontext :: (Context)
            _hdIover :: ([(Context,(Gens,Signatures))])
            _hdIsErr :: ([String])
            _hdOctxTree :: (Classification (Context,(Gens,Signatures)))
            _hdOctxs :: ([(Context,(Gens,Signatures))])
            _tlIcontexts :: (Contexts)
            _tlIover :: ([(Context,(Gens,Signatures))])
            _tlIsErr :: ([String])
            _tlOctxs :: ([(Context,(Gens,Signatures))])
            ( _hdIcontext,_hdIover,_hdIsErr) =
                (hd_ (_hdOctxTree) (_hdOctxs))
            ( _tlIcontexts,_tlIover,_tlIsErr) =
                (tl_ (_tlOctxs))
            -- "AGtry.ag"(line 74, column 10)
            (_hdOctxTree@_) =
                mkCtxAG _lhsIctxs (name _hdIcontext)
            -- "AGtry.ag"(line 73, column 10)
            (_lhsOover@_) =
                _hdIover ++ _tlIover
            -- "AGtry.ag"(line 263, column 10)
            (_lhsOsErr@_) =
                _hdIsErr ++ _tlIsErr
            -- "AGtry.ag"(line 406, column 10)
            (_lhsOcontexts@_) =
                _hdIcontext : _tlIcontexts
            -- copy rule (down)
            (_hdOctxs@_) =
                _lhsIctxs
            -- copy rule (down)
            (_tlOctxs@_) =
                _lhsIctxs
        in  ( _lhsOcontexts,_lhsOover,_lhsOsErr)
sem_Contexts_Nil :: (T_Contexts)
sem_Contexts_Nil  =
    \ _lhsIctxs ->
        let _lhsOcontexts :: (Contexts)
            _lhsOover :: ([(Context,(Gens,Signatures))])
            _lhsOsErr :: ([String])
            -- "AGtry.ag"(line 75, column 10)
            (_lhsOover@_) =
                []
            -- "AGtry.ag"(line 264, column 10)
            (_lhsOsErr@_) =
                []
            -- "AGtry.ag"(line 407, column 10)
            (_lhsOcontexts@_) =
                []
        in  ( _lhsOcontexts,_lhsOover,_lhsOsErr)
-- Expression --------------------------------------------------
{-
   inherited attributes:
      gE                   : GenR
      isign                : [(Concept,Concept)]
      mDef                 : Signatures
      pos                  : FilePos

   chained attributes:

   synthesised attributes:
      expr                 : Expression
      morphisms            : [Morphism]
      sErr                 : [String]
      signs                : [(Concept,Concept)]

-}
{-
   local variables for Expression.F:
      dis
      trpls
      sgns

-}
{-
   local variables for Expression.Fi:
      sgns

-}
{-
   local variables for Expression.Fu:
      sgns

-}
{-
   local variables for Expression.Tc:

-}
{-
   local variables for Expression.Tf:

-}
{-
   local variables for Expression.Tm:

-}
-- semantic domain
type T_Expression = (GenR) ->
                    ([(Concept,Concept)]) ->
                    (Signatures) ->
                    (FilePos) ->
                    ( (Expression),([Morphism]),([String]),([(Concept,Concept)]))
-- cata
sem_Expression :: (Expression) ->
                  (T_Expression)
sem_Expression ((F (_ts))) =
    (sem_Expression_F ((sem_Expressions (_ts))))
sem_Expression ((Fi (_fs))) =
    (sem_Expression_Fi ((sem_Expressions (_fs))))
sem_Expression ((Fu (_fs))) =
    (sem_Expression_Fu ((sem_Expressions (_fs))))
sem_Expression ((Tc (_c) (_compl))) =
    (sem_Expression_Tc ((sem_Expression (_c))) (_compl))
sem_Expression ((Tf (_f) (_compl))) =
    (sem_Expression_Tf ((sem_Morphism (_f))) (_compl))
sem_Expression ((Tm (_m) (_compl))) =
    (sem_Expression_Tm ((sem_Morphism (_m))) (_compl))
sem_Expression_F :: (T_Expressions) ->
                    (T_Expression)
sem_Expression_F (ts_) =
    \ _lhsIgE
      _lhsIisign
      _lhsImDef
      _lhsIpos ->
        let _lhsOexpr :: (Expression)
            _lhsOmorphisms :: ([Morphism])
            _lhsOsErr :: ([String])
            _lhsOsigns :: ([(Concept,Concept)])
            _tsIexprs :: (Expressions)
            _tsImorphisms :: ([Morphism])
            _tsIsErr :: ([String])
            _tsIsignss :: ([[(Concept,Concept)]])
            _tsOgE :: (GenR)
            _tsOisign :: ([(Concept,Concept)])
            _tsOmDef :: (Signatures)
            _tsOpos :: (FilePos)
            _tsOseptets :: ([(Concept, Expressions, [(Concept,Concept)], [Concept], [(Concept,Concept)], Expressions, Concept)])
            ( _tsIexprs,_tsImorphisms,_tsIsErr,_tsIsignss) =
                (ts_ (_tsOgE) (_tsOisign) (_tsOmDef) (_tsOpos) (_tsOseptets))
            -- "AGtry.ag"(line 198, column 8)
            (_tsOseptets@_) =
                _trpls
            -- "AGtry.ag"(line 192, column 8)
            (_dis@_) =
                F (if length _tsIexprs==1 then _tsIexprs else
                   distr (s,t) [cs|(a,l,sl,cs,sr,r,b)<- _trpls, a==s, b==t] _tsIexprs)
                where (s,t)= if null _lhsIisign then error("Fatal: ("++show _lhsIpos++") cannot compute distribution with empty @lhs.isign and @ts.exprs="++show _tsIexprs++
                                       "\n@trpls:     "++chain "\n->          " [show a++"#"++show ls++"#"++show sl++"#"++show cs++"#"++show sr++"#"++show rs++"#"++show b|(a,ls,sl,cs,sr,rs,b)<- _trpls])
                             else
                             head _lhsIisign
            -- "AGtry.ag"(line 191, column 8)
            (_lhsOexpr@_) =
                _dis
            -- "AGtry.ag"(line 184, column 8)
            (_trpls@_) =
                [ (a,l,sl,tlub _lhsIgE (rd(map snd sl)) (rd(map fst sr)),sr,r,b)
                | ((l,r),(sls,srs))<-zip (chop _tsIexprs) (chop _tsIsignss)
                , (a,b) <- take 1 _lhsIisign
                , sl <- [comps _lhsIgE sls]
                , sr <- [comps _lhsIgE srs]
                ]
            -- "AGtry.ag"(line 183, column 8)
            (_sgns@_) =
                comps _lhsIgE _tsIsignss
            -- "AGtry.ag"(line 182, column 8)
            (_lhsOsigns@_) =
                _sgns
            -- "AGtry.ag"(line 243, column 8)
            (_lhsOmorphisms@_) =
                _tsImorphisms
            -- "AGtry.ag"(line 315, column 8)
            (_lhsOsErr@_) =
                _tsIsErr++
                [ "5 in "++show _lhsIpos++"\n   Type error in composing\n   "++
                  show (F ls)++" :: "++shSigns sl++
                  " with\n   "++
                  show (F rs)++" :: "++shSigns sr++"\n"
                | (a,ls,sl,cs,sr,rs,b)<- _trpls
                , anything cs
                , not (and [isIdent m| m<-ls]&&anything sl)
                , not (and [isIdent m| m<-rs]&&anything sr)]++
                [ "6 in "++show _lhsIpos++"\n   Ambiguous composition of\n   "++
                  show (F ls)++" :: "++shSigns sl++
                  " with\n   "++
                  show (F rs)++" :: "++shSigns sr++
                  " over concepts "++show cs++"\n"
                |(a,ls,sl,cs,sr,rs,b)<- _trpls, length cs>1]
            -- copy rule (down)
            (_tsOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_tsOisign@_) =
                _lhsIisign
            -- copy rule (down)
            (_tsOmDef@_) =
                _lhsImDef
            -- copy rule (down)
            (_tsOpos@_) =
                _lhsIpos
        in  ( _lhsOexpr,_lhsOmorphisms,_lhsOsErr,_lhsOsigns)
sem_Expression_Fi :: (T_Expressions) ->
                     (T_Expression)
sem_Expression_Fi (fs_) =
    \ _lhsIgE
      _lhsIisign
      _lhsImDef
      _lhsIpos ->
        let _lhsOexpr :: (Expression)
            _lhsOmorphisms :: ([Morphism])
            _lhsOsErr :: ([String])
            _lhsOsigns :: ([(Concept,Concept)])
            _fsIexprs :: (Expressions)
            _fsImorphisms :: ([Morphism])
            _fsIsErr :: ([String])
            _fsIsignss :: ([[(Concept,Concept)]])
            _fsOgE :: (GenR)
            _fsOisign :: ([(Concept,Concept)])
            _fsOmDef :: (Signatures)
            _fsOpos :: (FilePos)
            _fsOseptets :: ([(Concept, Expressions, [(Concept,Concept)], [Concept], [(Concept,Concept)], Expressions, Concept)])
            ( _fsIexprs,_fsImorphisms,_fsIsErr,_fsIsignss) =
                (fs_ (_fsOgE) (_fsOisign) (_fsOmDef) (_fsOpos) (_fsOseptets))
            -- "AGtry.ag"(line 208, column 8)
            (_lhsOexpr@_) =
                Fi _fsIexprs
            -- "AGtry.ag"(line 207, column 8)
            (_fsOseptets@_) =
                []
            -- "AGtry.ag"(line 205, column 8)
            (_sgns@_) =
                if null _fsIsignss then error("Fatal: empty @fs.signss in expression "++showHS (Fi _fsIexprs)) else
                foldr1 (llub _lhsIgE) _fsIsignss
            -- "AGtry.ag"(line 204, column 8)
            (_lhsOsigns@_) =
                _sgns
            -- "AGtry.ag"(line 244, column 8)
            (_lhsOmorphisms@_) =
                _fsImorphisms
            -- "AGtry.ag"(line 345, column 8)
            (_lhsOsErr@_) =
                _fsIsErr++
                ["4 in "++show _lhsIpos++"\n   Incompatible concepts in comparing\n   "++
                 commaEng "and\n  " [show f++" :: "++shSigns s| (f,s)<-zip _fsIexprs _fsIsignss]++"\n"
                 |null _sgns]
            -- copy rule (down)
            (_fsOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_fsOisign@_) =
                _lhsIisign
            -- copy rule (down)
            (_fsOmDef@_) =
                _lhsImDef
            -- copy rule (down)
            (_fsOpos@_) =
                _lhsIpos
        in  ( _lhsOexpr,_lhsOmorphisms,_lhsOsErr,_lhsOsigns)
sem_Expression_Fu :: (T_Expressions) ->
                     (T_Expression)
sem_Expression_Fu (fs_) =
    \ _lhsIgE
      _lhsIisign
      _lhsImDef
      _lhsIpos ->
        let _lhsOexpr :: (Expression)
            _lhsOmorphisms :: ([Morphism])
            _lhsOsErr :: ([String])
            _lhsOsigns :: ([(Concept,Concept)])
            _fsIexprs :: (Expressions)
            _fsImorphisms :: ([Morphism])
            _fsIsErr :: ([String])
            _fsIsignss :: ([[(Concept,Concept)]])
            _fsOgE :: (GenR)
            _fsOisign :: ([(Concept,Concept)])
            _fsOmDef :: (Signatures)
            _fsOpos :: (FilePos)
            _fsOseptets :: ([(Concept, Expressions, [(Concept,Concept)], [Concept], [(Concept,Concept)], Expressions, Concept)])
            ( _fsIexprs,_fsImorphisms,_fsIsErr,_fsIsignss) =
                (fs_ (_fsOgE) (_fsOisign) (_fsOmDef) (_fsOpos) (_fsOseptets))
            -- "AGtry.ag"(line 203, column 8)
            (_lhsOexpr@_) =
                Fu _fsIexprs
            -- "AGtry.ag"(line 202, column 8)
            (_fsOseptets@_) =
                []
            -- "AGtry.ag"(line 200, column 8)
            (_sgns@_) =
                if null _fsIsignss then error("Fatal: empty @fs.signss in expression "++showHS (Fu _fsIexprs)) else
                foldr1 (llub _lhsIgE) _fsIsignss
            -- "AGtry.ag"(line 199, column 8)
            (_lhsOsigns@_) =
                _sgns
            -- "AGtry.ag"(line 245, column 8)
            (_lhsOmorphisms@_) =
                _fsImorphisms
            -- "AGtry.ag"(line 341, column 8)
            (_lhsOsErr@_) =
                _fsIsErr++
                ["4 in "++show _lhsIpos++"\n   Incompatible concepts in comparing\n   "++
                 commaEng "with\n  " [show f++" :: "++shSigns s| (f,s)<-zip _fsIexprs _fsIsignss]++"\n"
                 |null _sgns]
            -- copy rule (down)
            (_fsOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_fsOisign@_) =
                _lhsIisign
            -- copy rule (down)
            (_fsOmDef@_) =
                _lhsImDef
            -- copy rule (down)
            (_fsOpos@_) =
                _lhsIpos
        in  ( _lhsOexpr,_lhsOmorphisms,_lhsOsErr,_lhsOsigns)
sem_Expression_Tc :: (T_Expression) ->
                     (Bool) ->
                     (T_Expression)
sem_Expression_Tc (c_) (compl_) =
    \ _lhsIgE
      _lhsIisign
      _lhsImDef
      _lhsIpos ->
        let _lhsOexpr :: (Expression)
            _lhsOmorphisms :: ([Morphism])
            _lhsOsErr :: ([String])
            _lhsOsigns :: ([(Concept,Concept)])
            _cIexpr :: (Expression)
            _cImorphisms :: ([Morphism])
            _cIsErr :: ([String])
            _cIsigns :: ([(Concept,Concept)])
            _cOgE :: (GenR)
            _cOisign :: ([(Concept,Concept)])
            _cOmDef :: (Signatures)
            _cOpos :: (FilePos)
            ( _cIexpr,_cImorphisms,_cIsErr,_cIsigns) =
                (c_ (_cOgE) (_cOisign) (_cOmDef) (_cOpos))
            -- "AGtry.ag"(line 181, column 8)
            (_lhsOexpr@_) =
                Tc _cIexpr compl_
            -- "AGtry.ag"(line 180, column 8)
            (_lhsOsigns@_) =
                _cIsigns
            -- "AGtry.ag"(line 242, column 8)
            (_lhsOmorphisms@_) =
                _cImorphisms
            -- "AGtry.ag"(line 314, column 8)
            (_lhsOsErr@_) =
                _cIsErr
            -- copy rule (down)
            (_cOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_cOisign@_) =
                _lhsIisign
            -- copy rule (down)
            (_cOmDef@_) =
                _lhsImDef
            -- copy rule (down)
            (_cOpos@_) =
                _lhsIpos
        in  ( _lhsOexpr,_lhsOmorphisms,_lhsOsErr,_lhsOsigns)
sem_Expression_Tf :: (T_Morphism) ->
                     (Bool) ->
                     (T_Expression)
sem_Expression_Tf (f_) (compl_) =
    \ _lhsIgE
      _lhsIisign
      _lhsImDef
      _lhsIpos ->
        let _lhsOexpr :: (Expression)
            _lhsOmorphisms :: ([Morphism])
            _lhsOsErr :: ([String])
            _lhsOsigns :: ([(Concept,Concept)])
            _fIatts :: ([Concept])
            _fIid :: (Bool)
            _fImorphism :: (Morphism)
            _fImors :: (Signatures)
            _fInm :: (String)
            _fIpos :: (FilePos)
            _fIsErr :: ([String])
            _fIsigns :: ([(Concept,Concept)])
            _fOgE :: (GenR)
            _fOisign :: ([(Concept,Concept)])
            _fOmDef :: (Signatures)
            _fOpos :: (FilePos)
            ( _fIatts,_fIid,_fImorphism,_fImors,_fInm,_fIpos,_fIsErr,_fIsigns) =
                (f_ (_fOgE) (_fOisign) (_fOmDef) (_fOpos))
            -- "AGtry.ag"(line 179, column 8)
            (_lhsOexpr@_) =
                Tf _fImorphism compl_
            -- "AGtry.ag"(line 178, column 8)
            (_fOisign@_) =
                [ (b,a)| (a,b) <- _lhsIisign]
            -- "AGtry.ag"(line 177, column 8)
            (_lhsOsigns@_) =
                [ (b,a)| (a,b) <- _fIsigns]
            -- "AGtry.ag"(line 241, column 8)
            (_lhsOmorphisms@_) =
                [_fImorphism]
            -- "AGtry.ag"(line 313, column 8)
            (_lhsOsErr@_) =
                _fIsErr
            -- copy rule (down)
            (_fOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_fOmDef@_) =
                _lhsImDef
            -- copy rule (down)
            (_fOpos@_) =
                _lhsIpos
        in  ( _lhsOexpr,_lhsOmorphisms,_lhsOsErr,_lhsOsigns)
sem_Expression_Tm :: (T_Morphism) ->
                     (Bool) ->
                     (T_Expression)
sem_Expression_Tm (m_) (compl_) =
    \ _lhsIgE
      _lhsIisign
      _lhsImDef
      _lhsIpos ->
        let _lhsOexpr :: (Expression)
            _lhsOmorphisms :: ([Morphism])
            _lhsOsErr :: ([String])
            _lhsOsigns :: ([(Concept,Concept)])
            _mIatts :: ([Concept])
            _mIid :: (Bool)
            _mImorphism :: (Morphism)
            _mImors :: (Signatures)
            _mInm :: (String)
            _mIpos :: (FilePos)
            _mIsErr :: ([String])
            _mIsigns :: ([(Concept,Concept)])
            _mOgE :: (GenR)
            _mOisign :: ([(Concept,Concept)])
            _mOmDef :: (Signatures)
            _mOpos :: (FilePos)
            ( _mIatts,_mIid,_mImorphism,_mImors,_mInm,_mIpos,_mIsErr,_mIsigns) =
                (m_ (_mOgE) (_mOisign) (_mOmDef) (_mOpos))
            -- "AGtry.ag"(line 176, column 8)
            (_lhsOexpr@_) =
                Tm _mImorphism compl_
            -- "AGtry.ag"(line 175, column 8)
            (_lhsOsigns@_) =
                _mIsigns
            -- "AGtry.ag"(line 240, column 8)
            (_lhsOmorphisms@_) =
                [_mImorphism]
            -- "AGtry.ag"(line 312, column 8)
            (_lhsOsErr@_) =
                _mIsErr
            -- copy rule (down)
            (_mOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_mOisign@_) =
                _lhsIisign
            -- copy rule (down)
            (_mOmDef@_) =
                _lhsImDef
            -- copy rule (down)
            (_mOpos@_) =
                _lhsIpos
        in  ( _lhsOexpr,_lhsOmorphisms,_lhsOsErr,_lhsOsigns)
-- Expressions -------------------------------------------------
{-
   inherited attributes:
      gE                   : GenR
      isign                : [(Concept,Concept)]
      mDef                 : Signatures
      pos                  : FilePos
      septets              : [(Concept, Expressions, [(Concept,Concept)], [Concept], [(Concept,Concept)], Expressions, Concept)]

   chained attributes:

   synthesised attributes:
      exprs                : Expressions
      morphisms            : [Morphism]
      sErr                 : [String]
      signss               : [[(Concept,Concept)]]

-}
{-
   local variables for Expressions.Cons:
      septs
      hsgn

-}
{-
   local variables for Expressions.Nil:

-}
-- semantic domain
type T_Expressions = (GenR) ->
                     ([(Concept,Concept)]) ->
                     (Signatures) ->
                     (FilePos) ->
                     ([(Concept, Expressions, [(Concept,Concept)], [Concept], [(Concept,Concept)], Expressions, Concept)]) ->
                     ( (Expressions),([Morphism]),([String]),([[(Concept,Concept)]]))
-- cata
sem_Expressions :: (Expressions) ->
                   (T_Expressions)
sem_Expressions (list) =
    (foldr (sem_Expressions_Cons) (sem_Expressions_Nil) ((map sem_Expression list)))
sem_Expressions_Cons :: (T_Expression) ->
                        (T_Expressions) ->
                        (T_Expressions)
sem_Expressions_Cons (hd_) (tl_) =
    \ _lhsIgE
      _lhsIisign
      _lhsImDef
      _lhsIpos
      _lhsIseptets ->
        let _lhsOexprs :: (Expressions)
            _lhsOmorphisms :: ([Morphism])
            _lhsOsErr :: ([String])
            _lhsOsignss :: ([[(Concept,Concept)]])
            _hdIexpr :: (Expression)
            _hdImorphisms :: ([Morphism])
            _hdIsErr :: ([String])
            _hdIsigns :: ([(Concept,Concept)])
            _hdOgE :: (GenR)
            _hdOisign :: ([(Concept,Concept)])
            _hdOmDef :: (Signatures)
            _hdOpos :: (FilePos)
            _tlIexprs :: (Expressions)
            _tlImorphisms :: ([Morphism])
            _tlIsErr :: ([String])
            _tlIsignss :: ([[(Concept,Concept)]])
            _tlOgE :: (GenR)
            _tlOisign :: ([(Concept,Concept)])
            _tlOmDef :: (Signatures)
            _tlOpos :: (FilePos)
            _tlOseptets :: ([(Concept, Expressions, [(Concept,Concept)], [Concept], [(Concept,Concept)], Expressions, Concept)])
            ( _hdIexpr,_hdImorphisms,_hdIsErr,_hdIsigns) =
                (hd_ (_hdOgE) (_hdOisign) (_hdOmDef) (_hdOpos))
            ( _tlIexprs,_tlImorphisms,_tlIsErr,_tlIsignss) =
                (tl_ (_tlOgE) (_tlOisign) (_tlOmDef) (_tlOpos) (_tlOseptets))
            -- "AGtry.ag"(line 218, column 10)
            (_septs@_) =
                [ (c',tail l,rd[(c',c)|(a,c)<-sl],cs,sr,r,b)
                | (a,l,sl,cs,sr,r,b)<- _lhsIseptets,length l>1,(a',c')<- _hsgn]
            -- "AGtry.ag"(line 217, column 10)
            (_tlOseptets@_) =
                _septs
            -- "AGtry.ag"(line 215, column 10)
            (_tlOisign@_) =
                if null _lhsIseptets then _lhsIisign else
                [(c,b)| (a,l,sl,cs,sr,r,b)<- _lhsIseptets, length l==1, c<-cs]
            -- "AGtry.ag"(line 214, column 10)
            (_hsgn@_) =
                [(a,c)| (a,l,sl,cs,sr,r,b)<- _lhsIseptets, length l==1, c<-cs]
            -- "AGtry.ag"(line 211, column 10)
            (_hdOisign@_) =
                if null _lhsIseptets then _lhsIisign else
                _hsgn
            -- "AGtry.ag"(line 210, column 10)
            (_lhsOsignss@_) =
                _hdIsigns: _tlIsignss
            -- "AGtry.ag"(line 247, column 10)
            (_lhsOmorphisms@_) =
                _hdImorphisms ++ _tlImorphisms
            -- "AGtry.ag"(line 363, column 10)
            (_lhsOsErr@_) =
                _hdIsErr ++ _tlIsErr
            -- "AGtry.ag"(line 447, column 10)
            (_lhsOexprs@_) =
                _hdIexpr : _tlIexprs
            -- copy rule (down)
            (_hdOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_hdOmDef@_) =
                _lhsImDef
            -- copy rule (down)
            (_hdOpos@_) =
                _lhsIpos
            -- copy rule (down)
            (_tlOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_tlOmDef@_) =
                _lhsImDef
            -- copy rule (down)
            (_tlOpos@_) =
                _lhsIpos
        in  ( _lhsOexprs,_lhsOmorphisms,_lhsOsErr,_lhsOsignss)
sem_Expressions_Nil :: (T_Expressions)
sem_Expressions_Nil  =
    \ _lhsIgE
      _lhsIisign
      _lhsImDef
      _lhsIpos
      _lhsIseptets ->
        let _lhsOexprs :: (Expressions)
            _lhsOmorphisms :: ([Morphism])
            _lhsOsErr :: ([String])
            _lhsOsignss :: ([[(Concept,Concept)]])
            -- "AGtry.ag"(line 220, column 10)
            (_lhsOsignss@_) =
                []
            -- "AGtry.ag"(line 248, column 10)
            (_lhsOmorphisms@_) =
                []
            -- "AGtry.ag"(line 369, column 10)
            (_lhsOsErr@_) =
                []
            -- "AGtry.ag"(line 448, column 10)
            (_lhsOexprs@_) =
                []
        in  ( _lhsOexprs,_lhsOmorphisms,_lhsOsErr,_lhsOsignss)
-- Gen ---------------------------------------------------------
{-
   inherited attributes:
      gE                   : GenR

   chained attributes:

   synthesised attributes:
      gen                  : Gen

-}
{-
   local variables for Gen.G:

-}
-- semantic domain
type T_Gen = (GenR) ->
             ( (Gen))
-- cata
sem_Gen :: (Gen) ->
           (T_Gen)
sem_Gen ((G (_genus) (_spec))) =
    (sem_Gen_G ((sem_Concept (_genus))) ((sem_Concept (_spec))))
sem_Gen_G :: (T_Concept) ->
             (T_Concept) ->
             (T_Gen)
sem_Gen_G (genus_) (spec_) =
    \ _lhsIgE ->
        let _lhsOgen :: (Gen)
            _genusIconcept :: (Concept)
            _genusInm :: (String)
            _genusOgE :: (GenR)
            _specIconcept :: (Concept)
            _specInm :: (String)
            _specOgE :: (GenR)
            ( _genusIconcept,_genusInm) =
                (genus_ (_genusOgE))
            ( _specIconcept,_specInm) =
                (spec_ (_specOgE))
            -- "AGtry.ag"(line 474, column 7)
            (_lhsOgen@_) =
                G _genusIconcept _specIconcept
            -- copy rule (down)
            (_genusOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_specOgE@_) =
                _lhsIgE
        in  ( _lhsOgen)
-- Gens --------------------------------------------------------
{-
   inherited attributes:
      gE                   : GenR

   chained attributes:

   synthesised attributes:
      list                 : Gens

-}
{-
   local variables for Gens.Cons:

-}
{-
   local variables for Gens.Nil:

-}
-- semantic domain
type T_Gens = (GenR) ->
              ( (Gens))
-- cata
sem_Gens :: (Gens) ->
            (T_Gens)
sem_Gens (list) =
    (foldr (sem_Gens_Cons) (sem_Gens_Nil) ((map sem_Gen list)))
sem_Gens_Cons :: (T_Gen) ->
                 (T_Gens) ->
                 (T_Gens)
sem_Gens_Cons (hd_) (tl_) =
    \ _lhsIgE ->
        let _lhsOlist :: (Gens)
            _hdIgen :: (Gen)
            _hdOgE :: (GenR)
            _tlIlist :: (Gens)
            _tlOgE :: (GenR)
            ( _hdIgen) =
                (hd_ (_hdOgE))
            ( _tlIlist) =
                (tl_ (_tlOgE))
            -- "AGtry.ag"(line 469, column 10)
            (_lhsOlist@_) =
                _hdIgen : _tlIlist
            -- copy rule (down)
            (_hdOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_tlOgE@_) =
                _lhsIgE
        in  ( _lhsOlist)
sem_Gens_Nil :: (T_Gens)
sem_Gens_Nil  =
    \ _lhsIgE ->
        let _lhsOlist :: (Gens)
            -- "AGtry.ag"(line 470, column 10)
            (_lhsOlist@_) =
                []
        in  ( _lhsOlist)
-- Links -------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Links.Cons:

-}
{-
   local variables for Links.Nil:

-}
-- semantic domain
type T_Links = ( )
-- cata
sem_Links :: (Links) ->
             (T_Links)
sem_Links (list) =
    (foldr (sem_Links_Cons) (sem_Links_Nil) (list))
sem_Links_Cons :: (Link) ->
                  (T_Links) ->
                  (T_Links)
sem_Links_Cons (hd_) (tl_) =
    let 
    in  ( )
sem_Links_Nil :: (T_Links)
sem_Links_Nil  =
    let 
    in  ( )
-- Morphism ----------------------------------------------------
{-
   inherited attributes:
      gE                   : GenR
      isign                : [(Concept,Concept)]
      mDef                 : Signatures

   chained attributes:
      pos                  : FilePos

   synthesised attributes:
      atts                 : [Concept]
      id                   : Bool
      morphism             : Morphism
      mors                 : Signatures
      nm                   : String
      sErr                 : [String]
      signs                : [(Concept,Concept)]

-}
{-
   local variables for Morphism.Id:
      ats

-}
{-
   local variables for Morphism.Mph:
      is
      ms'
      ms
      ats
      m
      s
      rel

-}
-- semantic domain
type T_Morphism = (GenR) ->
                  ([(Concept,Concept)]) ->
                  (Signatures) ->
                  (FilePos) ->
                  ( ([Concept]),(Bool),(Morphism),(Signatures),(String),(FilePos),([String]),([(Concept,Concept)]))
-- cata
sem_Morphism :: (Morphism) ->
                (T_Morphism)
sem_Morphism ((Id (_pos) (_atts) (_c))) =
    (sem_Morphism_Id (_pos) (_atts) ((sem_Concept (_c))))
sem_Morphism ((Mph (_nm) (_pos) (_atts) (_sgn) (_m))) =
    (sem_Morphism_Mph (_nm) (_pos) (_atts) (_sgn) ((sem_Signature (_m))))
sem_Morphism_Id :: (FilePos) ->
                   ([Concept]) ->
                   (T_Concept) ->
                   (T_Morphism)
sem_Morphism_Id (pos_) (atts_) (c_) =
    \ _lhsIgE
      _lhsIisign
      _lhsImDef
      _lhsIpos ->
        let _lhsOatts :: ([Concept])
            _lhsOid :: (Bool)
            _lhsOmorphism :: (Morphism)
            _lhsOmors :: (Signatures)
            _lhsOnm :: (String)
            _lhsOpos :: (FilePos)
            _lhsOsErr :: ([String])
            _lhsOsigns :: ([(Concept,Concept)])
            _cIconcept :: (Concept)
            _cInm :: (String)
            _cOgE :: (GenR)
            ( _cIconcept,_cInm) =
                (c_ (_cOgE))
            -- "AGtry.ag"(line 225, column 9)
            (_lhsOsigns@_) =
                if null atts_ then [(Anything _lhsIgE,Anything _lhsIgE)] else [(a,a)|a <- atts_]
            -- "AGtry.ag"(line 256, column 9)
            (_lhsOmors@_) =
                []
            -- "AGtry.ag"(line 399, column 9)
            (_lhsOsErr@_) =
                []
            -- "AGtry.ag"(line 508, column 9)
            (_lhsOid@_) =
                True
            -- "AGtry.ag"(line 507, column 9)
            (_ats@_) =
                rd [C a _lhsIgE as|C a _ as<- atts_]
            -- "AGtry.ag"(line 506, column 9)
            (_lhsOatts@_) =
                _ats
            -- "AGtry.ag"(line 505, column 9)
            (_lhsOpos@_) =
                pos_
            -- "AGtry.ag"(line 504, column 9)
            (_lhsOnm@_) =
                "I"
            -- "AGtry.ag"(line 501, column 9)
            (_lhsOmorphism@_) =
                Id pos_ _ats (if s `_lhsIgE` t then t else s)
                where (s,t) = if null _lhsIisign then error ("Fatal: null @lhs.isign in Id lhs.morphism!") else
                              head _lhsIisign
            -- copy rule (down)
            (_cOgE@_) =
                _lhsIgE
        in  ( _lhsOatts,_lhsOid,_lhsOmorphism,_lhsOmors,_lhsOnm,_lhsOpos,_lhsOsErr,_lhsOsigns)
sem_Morphism_Mph :: (String) ->
                    (FilePos) ->
                    ([Concept]) ->
                    ((Concept,Concept)) ->
                    (T_Signature) ->
                    (T_Morphism)
sem_Morphism_Mph (nm_) (pos_) (atts_) (sgn_) (m_) =
    \ _lhsIgE
      _lhsIisign
      _lhsImDef
      _lhsIpos ->
        let _lhsOatts :: ([Concept])
            _lhsOid :: (Bool)
            _lhsOmorphism :: (Morphism)
            _lhsOmors :: (Signatures)
            _lhsOnm :: (String)
            _lhsOpos :: (FilePos)
            _lhsOsErr :: ([String])
            _lhsOsigns :: ([(Concept,Concept)])
            _mInm :: (String)
            _mIsErr :: ([String])
            _mIsignature :: (Signature)
            _mOgE :: (GenR)
            ( _mInm,_mIsErr,_mIsignature) =
                (m_ (_mOgE))
            -- "AGtry.ag"(line 223, column 9)
            (_is@_) =
                irredM _lhsIgE [ mor | mor <- _ms'
                                     , or[source mor `_lhsIgE` a && target mor `_lhsIgE` b|(a,b) <- _lhsIisign]  ]
            -- "AGtry.ag"(line 222, column 9)
            (_lhsOsigns@_) =
                if null atts_ then [ (source mor,target mor) | mor <- _ms'] else [(head atts_,last atts_)]
            -- "AGtry.ag"(line 254, column 9)
            (_ms'@_) =
                if null atts_ then _ms else
                [ mor | mor <- _ms, source mor == head atts_, target mor == last atts_]
            -- "AGtry.ag"(line 253, column 9)
            (_ms@_) =
                [ mor | mor <- _lhsImDef, name mor == nm_]
            -- "AGtry.ag"(line 252, column 9)
            (_lhsOmors@_) =
                _ms'
            -- "AGtry.ag"(line 384, column 9)
            (_lhsOsErr@_) =
                [ "7 in "++show pos_++
                  "\n   Relation "++show (Mph nm_ pos_ atts_ (Anything _lhsIgE,Anything (==)) (Idn (Anything (==)) posNone))++"\n   has more than two concepts.\n"
                | length atts_ >2 ]++
                [ "3 in "++show pos_++
                  "\n   Relation " ++ show (Mph nm_ pos_ atts_ (Anything (==),Anything (==)) (Idn (Anything (==)) posNone)) ++
                  (if null atts_ then "" else show (rd atts_)) ++
                  " is not defined.\n"
                | _ms'==[]]
            -- "AGtry.ag"(line 500, column 9)
            (_lhsOid@_) =
                False
            -- "AGtry.ag"(line 499, column 9)
            (_ats@_) =
                rd [C a _lhsIgE as|C a _ as<- atts_]
            -- "AGtry.ag"(line 498, column 9)
            (_lhsOatts@_) =
                _ats
            -- "AGtry.ag"(line 497, column 9)
            (_lhsOpos@_) =
                pos_
            -- "AGtry.ag"(line 496, column 9)
            (_lhsOnm@_) =
                nm_
            -- "AGtry.ag"(line 490, column 9)
            (_m@_) =
                if null _is
                then error("Fatal 3: Empty signature allocation for "++show nm_++" on "++show pos_++":\n  @lhs.isign="++show _lhsIisign++":\n  @ms="++chain "\n       " (map show _ms)++":\n  @ms'="++chain "\n       " (map show _ms'))
                else if length _is>1
                then error("Fatal 6: Ambiguous signature allocation for "++show nm_++" on "++show pos_++":\n   "++
                                                     chain "\n   " (map show _is))
                else head _is
            -- "AGtry.ag"(line 487, column 9)
            (_s@_) =
                if null _lhsIisign
                then error("Fatal 2: Empty signature allocation for "++ nm_ ++" on "++show pos_++":\n  @ms="++chain "\n       " (map show _ms)++":\n  @ms'="++chain "\n       " (map show _ms'))
                else head _lhsIisign
            -- "AGtry.ag"(line 486, column 9)
            (_rel@_) =
                [m| m <- _ms', source m `_lhsIgE` fst _s && target m `_lhsIgE` snd _s]
            -- "AGtry.ag"(line 483, column 9)
            (_lhsOmorphism@_) =
                Mph nm_ pos_ _ats _s
                    (if null _rel then error("Fatal: null @rel in "++ nm_++" on "++show pos_++"\n@lhs.isign = "++ show _lhsIisign++"\n@ms'       = "++ show _ms'++"\n@s         = "++ show _s++"\n"++ gEtabG _lhsIgE (rd ([fst _s,snd _s]++concs _ms'))) else
                     head _rel)
            -- copy rule (down)
            (_mOgE@_) =
                _lhsIgE
        in  ( _lhsOatts,_lhsOid,_lhsOmorphism,_lhsOmors,_lhsOnm,_lhsOpos,_lhsOsErr,_lhsOsigns)
-- Pattern -----------------------------------------------------
{-
   inherited attributes:
      gE                   : GenR
      mDef                 : Signatures

   chained attributes:
      nr                   : Int

   synthesised attributes:
      conDefs              : [ConceptDef]
      mGen                 : Gens
      morphisms            : [Morphism]
      pattern              : Pattern
      sErr                 : [String]
      signatures           : Signatures

-}
{-
   local variables for Pattern.Pat:

-}
-- semantic domain
type T_Pattern = (GenR) ->
                 (Signatures) ->
                 (Int) ->
                 ( ([ConceptDef]),(Gens),([Morphism]),(Int),(Pattern),([String]),(Signatures))
-- cata
sem_Pattern :: (Pattern) ->
               (T_Pattern)
sem_Pattern ((Pat (_nm) (_rules) (_gen) (_pms) (_cs))) =
    (sem_Pattern_Pat (_nm) ((sem_Rules (_rules))) ((sem_Gens (_gen))) ((sem_Signatures (_pms))) ((sem_ConceptDefs (_cs))))
sem_Pattern_Pat :: (String) ->
                   (T_Rules) ->
                   (T_Gens) ->
                   (T_Signatures) ->
                   (T_ConceptDefs) ->
                   (T_Pattern)
sem_Pattern_Pat (nm_) (rules_) (gen_) (pms_) (cs_) =
    \ _lhsIgE
      _lhsImDef
      _lhsInr ->
        let _lhsOconDefs :: ([ConceptDef])
            _lhsOmGen :: (Gens)
            _lhsOmorphisms :: ([Morphism])
            _lhsOnr :: (Int)
            _lhsOpattern :: (Pattern)
            _lhsOsErr :: ([String])
            _lhsOsignatures :: (Signatures)
            _rulesImGen :: (Gens)
            _rulesImorphisms :: ([Morphism])
            _rulesInr :: (Int)
            _rulesIrules :: (Rules)
            _rulesIsErr :: ([String])
            _rulesOgE :: (GenR)
            _rulesOmDef :: (Signatures)
            _rulesOnr :: (Int)
            _genIlist :: (Gens)
            _genOgE :: (GenR)
            _pmsIsErr :: ([String])
            _pmsIsignatures :: (Signatures)
            _pmsOgE :: (GenR)
            _csIconDefs :: ([ConceptDef])
            ( _rulesImGen,_rulesImorphisms,_rulesInr,_rulesIrules,_rulesIsErr) =
                (rules_ (_rulesOgE) (_rulesOmDef) (_rulesOnr))
            ( _genIlist) =
                (gen_ (_genOgE))
            ( _pmsIsErr,_pmsIsignatures) =
                (pms_ (_pmsOgE))
            ( _csIconDefs) =
                (cs_ )
            -- "AGtry.ag"(line 99, column 9)
            (_lhsOmGen@_) =
                clearG (_rulesImGen ++ _genIlist)
            -- "AGtry.ag"(line 232, column 9)
            (_lhsOmorphisms@_) =
                _rulesImorphisms
            -- "AGtry.ag"(line 271, column 9)
            (_lhsOsErr@_) =
                _rulesIsErr ++ _pmsIsErr
            -- "AGtry.ag"(line 428, column 9)
            (_lhsOconDefs@_) =
                _csIconDefs
            -- "AGtry.ag"(line 427, column 9)
            (_lhsOsignatures@_) =
                _pmsIsignatures
            -- "AGtry.ag"(line 426, column 9)
            (_lhsOnr@_) =
                _rulesInr
            -- "AGtry.ag"(line 425, column 9)
            (_lhsOpattern@_) =
                Pat nm_ _rulesIrules _genIlist _pmsIsignatures _csIconDefs
            -- copy rule (down)
            (_rulesOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_rulesOmDef@_) =
                _lhsImDef
            -- copy rule (down)
            (_rulesOnr@_) =
                _lhsInr
            -- copy rule (down)
            (_genOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_pmsOgE@_) =
                _lhsIgE
        in  ( _lhsOconDefs,_lhsOmGen,_lhsOmorphisms,_lhsOnr,_lhsOpattern,_lhsOsErr,_lhsOsignatures)
-- Patterns ----------------------------------------------------
{-
   inherited attributes:
      gE                   : GenR
      mDef                 : Signatures

   chained attributes:
      nr                   : Int

   synthesised attributes:
      conDefs              : [ConceptDef]
      mGen                 : Gens
      morphisms            : [Morphism]
      patterns             : Patterns
      sErr                 : [String]
      signatures           : Signatures

-}
{-
   local variables for Patterns.Cons:

-}
{-
   local variables for Patterns.Nil:

-}
-- semantic domain
type T_Patterns = (GenR) ->
                  (Signatures) ->
                  (Int) ->
                  ( ([ConceptDef]),(Gens),([Morphism]),(Int),(Patterns),([String]),(Signatures))
-- cata
sem_Patterns :: (Patterns) ->
                (T_Patterns)
sem_Patterns (list) =
    (foldr (sem_Patterns_Cons) (sem_Patterns_Nil) ((map sem_Pattern list)))
sem_Patterns_Cons :: (T_Pattern) ->
                     (T_Patterns) ->
                     (T_Patterns)
sem_Patterns_Cons (hd_) (tl_) =
    \ _lhsIgE
      _lhsImDef
      _lhsInr ->
        let _lhsOconDefs :: ([ConceptDef])
            _lhsOmGen :: (Gens)
            _lhsOmorphisms :: ([Morphism])
            _lhsOnr :: (Int)
            _lhsOpatterns :: (Patterns)
            _lhsOsErr :: ([String])
            _lhsOsignatures :: (Signatures)
            _hdIconDefs :: ([ConceptDef])
            _hdImGen :: (Gens)
            _hdImorphisms :: ([Morphism])
            _hdInr :: (Int)
            _hdIpattern :: (Pattern)
            _hdIsErr :: ([String])
            _hdIsignatures :: (Signatures)
            _hdOgE :: (GenR)
            _hdOmDef :: (Signatures)
            _hdOnr :: (Int)
            _tlIconDefs :: ([ConceptDef])
            _tlImGen :: (Gens)
            _tlImorphisms :: ([Morphism])
            _tlInr :: (Int)
            _tlIpatterns :: (Patterns)
            _tlIsErr :: ([String])
            _tlIsignatures :: (Signatures)
            _tlOgE :: (GenR)
            _tlOmDef :: (Signatures)
            _tlOnr :: (Int)
            ( _hdIconDefs,_hdImGen,_hdImorphisms,_hdInr,_hdIpattern,_hdIsErr,_hdIsignatures) =
                (hd_ (_hdOgE) (_hdOmDef) (_hdOnr))
            ( _tlIconDefs,_tlImGen,_tlImorphisms,_tlInr,_tlIpatterns,_tlIsErr,_tlIsignatures) =
                (tl_ (_tlOgE) (_tlOmDef) (_tlOnr))
            -- "AGtry.ag"(line 96, column 10)
            (_lhsOmGen@_) =
                _hdImGen ++ _tlImGen
            -- "AGtry.ag"(line 229, column 10)
            (_lhsOmorphisms@_) =
                _hdImorphisms ++ _tlImorphisms
            -- "AGtry.ag"(line 268, column 10)
            (_lhsOsErr@_) =
                _hdIsErr ++ _tlIsErr
            -- "AGtry.ag"(line 417, column 10)
            (_lhsOconDefs@_) =
                _hdIconDefs ++ _tlIconDefs
            -- "AGtry.ag"(line 416, column 10)
            (_lhsOsignatures@_) =
                _hdIsignatures ++ _tlIsignatures
            -- "AGtry.ag"(line 415, column 10)
            (_lhsOnr@_) =
                _tlInr
            -- "AGtry.ag"(line 414, column 10)
            (_lhsOpatterns@_) =
                _hdIpattern : _tlIpatterns
            -- copy rule (down)
            (_hdOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_hdOmDef@_) =
                _lhsImDef
            -- copy rule (down)
            (_hdOnr@_) =
                _lhsInr
            -- copy rule (down)
            (_tlOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_tlOmDef@_) =
                _lhsImDef
            -- copy rule (chain)
            (_tlOnr@_) =
                _hdInr
        in  ( _lhsOconDefs,_lhsOmGen,_lhsOmorphisms,_lhsOnr,_lhsOpatterns,_lhsOsErr,_lhsOsignatures)
sem_Patterns_Nil :: (T_Patterns)
sem_Patterns_Nil  =
    \ _lhsIgE
      _lhsImDef
      _lhsInr ->
        let _lhsOconDefs :: ([ConceptDef])
            _lhsOmGen :: (Gens)
            _lhsOmorphisms :: ([Morphism])
            _lhsOnr :: (Int)
            _lhsOpatterns :: (Patterns)
            _lhsOsErr :: ([String])
            _lhsOsignatures :: (Signatures)
            -- "AGtry.ag"(line 97, column 10)
            (_lhsOmGen@_) =
                []
            -- "AGtry.ag"(line 230, column 10)
            (_lhsOmorphisms@_) =
                []
            -- "AGtry.ag"(line 269, column 10)
            (_lhsOsErr@_) =
                []
            -- "AGtry.ag"(line 421, column 10)
            (_lhsOconDefs@_) =
                []
            -- "AGtry.ag"(line 420, column 10)
            (_lhsOsignatures@_) =
                []
            -- "AGtry.ag"(line 419, column 10)
            (_lhsOnr@_) =
                _lhsInr
            -- "AGtry.ag"(line 418, column 10)
            (_lhsOpatterns@_) =
                []
        in  ( _lhsOconDefs,_lhsOmGen,_lhsOmorphisms,_lhsOnr,_lhsOpatterns,_lhsOsErr,_lhsOsignatures)
-- Prop --------------------------------------------------------
{-
   inherited attributes:

   chained attributes:

   synthesised attributes:

-}
{-
   local variables for Prop.Asy:

-}
{-
   local variables for Prop.Inj:

-}
{-
   local variables for Prop.Sur:

-}
{-
   local variables for Prop.Sym:

-}
{-
   local variables for Prop.Tot:

-}
{-
   local variables for Prop.Trn:

-}
{-
   local variables for Prop.Uni:

-}
-- semantic domain
type T_Prop = ( )
-- cata
sem_Prop :: (Prop) ->
            (T_Prop)
sem_Prop ((Asy )) =
    (sem_Prop_Asy )
sem_Prop ((Inj )) =
    (sem_Prop_Inj )
sem_Prop ((Sur )) =
    (sem_Prop_Sur )
sem_Prop ((Sym )) =
    (sem_Prop_Sym )
sem_Prop ((Tot )) =
    (sem_Prop_Tot )
sem_Prop ((Trn )) =
    (sem_Prop_Trn )
sem_Prop ((Uni )) =
    (sem_Prop_Uni )
sem_Prop_Asy :: (T_Prop)
sem_Prop_Asy  =
    let 
    in  ( )
sem_Prop_Inj :: (T_Prop)
sem_Prop_Inj  =
    let 
    in  ( )
sem_Prop_Sur :: (T_Prop)
sem_Prop_Sur  =
    let 
    in  ( )
sem_Prop_Sym :: (T_Prop)
sem_Prop_Sym  =
    let 
    in  ( )
sem_Prop_Tot :: (T_Prop)
sem_Prop_Tot  =
    let 
    in  ( )
sem_Prop_Trn :: (T_Prop)
sem_Prop_Trn  =
    let 
    in  ( )
sem_Prop_Uni :: (T_Prop)
sem_Prop_Uni  =
    let 
    in  ( )
-- Rule --------------------------------------------------------
{-
   inherited attributes:
      gE                   : GenR
      mDef                 : Signatures
      nr                   : Int

   chained attributes:

   synthesised attributes:
      mGen                 : Gens
      morphisms            : [Morphism]
      rules                : Rules
      sErr                 : [String]

-}
{-
   local variables for Rule.Gc:
      esign
      ms

-}
{-
   local variables for Rule.Ru:
      is
      s
      r

-}
-- semantic domain
type T_Rule = (GenR) ->
              (Signatures) ->
              (Int) ->
              ( (Gens),([Morphism]),(Rules),([String]))
-- cata
sem_Rule :: (Rule) ->
            (T_Rule)
sem_Rule ((Gc (_gluePos) (_m) (_expr) (_sgn) (_nr))) =
    (sem_Rule_Gc (_gluePos) ((sem_Morphism (_m))) ((sem_Expression (_expr))) (_sgn) (_nr))
sem_Rule ((Ru (_c) (_antc) (_rulePos) (_cons) (_expl) (_sgn) (_nr))) =
    (sem_Rule_Ru (_c) ((sem_Expression (_antc))) (_rulePos) ((sem_Expression (_cons))) (_expl) (_sgn) (_nr))
sem_Rule_Gc :: (FilePos) ->
               (T_Morphism) ->
               (T_Expression) ->
               ((Concept,Concept)) ->
               (Int) ->
               (T_Rule)
sem_Rule_Gc (gluePos_) (m_) (expr_) (sgn_) (nr_) =
    \ _lhsIgE
      _lhsImDef
      _lhsInr ->
        let _lhsOmGen :: (Gens)
            _lhsOmorphisms :: ([Morphism])
            _lhsOrules :: (Rules)
            _lhsOsErr :: ([String])
            _mIatts :: ([Concept])
            _mIid :: (Bool)
            _mImorphism :: (Morphism)
            _mImors :: (Signatures)
            _mInm :: (String)
            _mIpos :: (FilePos)
            _mIsErr :: ([String])
            _mIsigns :: ([(Concept,Concept)])
            _mOgE :: (GenR)
            _mOisign :: ([(Concept,Concept)])
            _mOmDef :: (Signatures)
            _mOpos :: (FilePos)
            _exprIexpr :: (Expression)
            _exprImorphisms :: ([Morphism])
            _exprIsErr :: ([String])
            _exprIsigns :: ([(Concept,Concept)])
            _exprOgE :: (GenR)
            _exprOisign :: ([(Concept,Concept)])
            _exprOmDef :: (Signatures)
            _exprOpos :: (FilePos)
            ( _mIatts,_mIid,_mImorphism,_mImors,_mInm,_mIpos,_mIsErr,_mIsigns) =
                (m_ (_mOgE) (_mOisign) (_mOmDef) (_mOpos))
            ( _exprIexpr,_exprImorphisms,_exprIsErr,_exprIsigns) =
                (expr_ (_exprOgE) (_exprOisign) (_exprOmDef) (_exprOpos))
            -- "AGtry.ag"(line 105, column 8)
            (_lhsOmGen@_) =
                clearG [g| (d,c) <- _exprIsigns, m <- _mImors, g<-[G d (source m), G c (target m)]]
            -- "AGtry.ag"(line 134, column 8)
            (_mOpos@_) =
                gluePos_
            -- "AGtry.ag"(line 133, column 8)
            (_exprOpos@_) =
                gluePos_
            -- "AGtry.ag"(line 132, column 8)
            (_esign@_) =
                irredT _lhsIgE _exprIsigns
            -- "AGtry.ag"(line 125, column 8)
            (_ms@_) =
                irredT _lhsIgE
                 (if null _exprIsigns
                  then [(source m,target m)| m <- _mImors]
                  else [(source m,target m)| m <- _mImors
                                           , or[s `_lhsIgE` source m && t `_lhsIgE` target m
                                               | (s,t) <- _exprIsigns ]
                       ])
            -- "AGtry.ag"(line 124, column 8)
            (_exprOisign@_) =
                irredT _lhsIgE _exprIsigns
            -- "AGtry.ag"(line 123, column 8)
            (_mOisign@_) =
                _ms
            -- "AGtry.ag"(line 238, column 8)
            (_lhsOmorphisms@_) =
                _mImorphism : _exprImorphisms
            -- "AGtry.ag"(line 297, column 8)
            (_lhsOsErr@_) =
                take 1
                 (  [ "12 in "++show gluePos_++
                      "\n   I not allowed as left hand side of GLUE\n"
                    | null _ms && _mIid]
                 ++ ["13 in "++show gluePos_++
                      "\n   I not allowed as right hand side of GLUE\n"
                    | anything _exprIsigns]
                 ++ _mIsErr ++ _exprIsErr
                 )
            -- "AGtry.ag"(line 462, column 8)
            (_lhsOrules@_) =
                [Gc gluePos_ (Mph _mInm _mIpos _mIatts sgn m) (_exprIexpr) sgn  _lhsInr
                | (d,c) <- _exprIsigns, m <- _mImors
                , d `_lhsIgE` source m, c `_lhsIgE` target m
                , sgn<-[if null _mIatts then (source m,target m) else (head _mIatts,last _mIatts)]]
            -- copy rule (down)
            (_mOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_mOmDef@_) =
                _lhsImDef
            -- copy rule (down)
            (_exprOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_exprOmDef@_) =
                _lhsImDef
        in  ( _lhsOmGen,_lhsOmorphisms,_lhsOrules,_lhsOsErr)
sem_Rule_Ru :: (Char) ->
               (T_Expression) ->
               (FilePos) ->
               (T_Expression) ->
               (String) ->
               ((Concept,Concept)) ->
               (Int) ->
               (T_Rule)
sem_Rule_Ru (c_) (antc_) (rulePos_) (cons_) (expl_) (sgn_) (nr_) =
    \ _lhsIgE
      _lhsImDef
      _lhsInr ->
        let _lhsOmGen :: (Gens)
            _lhsOmorphisms :: ([Morphism])
            _lhsOrules :: (Rules)
            _lhsOsErr :: ([String])
            _antcIexpr :: (Expression)
            _antcImorphisms :: ([Morphism])
            _antcIsErr :: ([String])
            _antcIsigns :: ([(Concept,Concept)])
            _antcOgE :: (GenR)
            _antcOisign :: ([(Concept,Concept)])
            _antcOmDef :: (Signatures)
            _antcOpos :: (FilePos)
            _consIexpr :: (Expression)
            _consImorphisms :: ([Morphism])
            _consIsErr :: ([String])
            _consIsigns :: ([(Concept,Concept)])
            _consOgE :: (GenR)
            _consOisign :: ([(Concept,Concept)])
            _consOmDef :: (Signatures)
            _consOpos :: (FilePos)
            ( _antcIexpr,_antcImorphisms,_antcIsErr,_antcIsigns) =
                (antc_ (_antcOgE) (_antcOisign) (_antcOmDef) (_antcOpos))
            ( _consIexpr,_consImorphisms,_consIsErr,_consIsigns) =
                (cons_ (_consOgE) (_consOisign) (_consOmDef) (_consOpos))
            -- "AGtry.ag"(line 104, column 8)
            (_lhsOmGen@_) =
                []
            -- "AGtry.ag"(line 122, column 8)
            (_consOpos@_) =
                rulePos_
            -- "AGtry.ag"(line 121, column 8)
            (_antcOpos@_) =
                rulePos_
            -- "AGtry.ag"(line 120, column 8)
            (_consOisign@_) =
                if null _is then _consIsigns else _is
            -- "AGtry.ag"(line 119, column 8)
            (_antcOisign@_) =
                if null _is then _antcIsigns else _is
            -- "AGtry.ag"(line 112, column 8)
            (_is@_) =
                if null _antcIsigns
                then if null _consIsigns
                     then []
                     else _consIsigns
                else if null _consIsigns
                     then _antcIsigns
                     else _s
            -- "AGtry.ag"(line 108, column 8)
            (_s@_) =
                irredT _lhsIgE [ (if a `_lhsIgE` a' then a' else a, if b `_lhsIgE` b' then b' else b)
                               | (a,b)<- _consIsigns, (a',b')<- _antcIsigns
                               , (a `_lhsIgE` a' || a' `_lhsIgE` a) && (b `_lhsIgE` b' || b' `_lhsIgE` b)
                               ]
            -- "AGtry.ag"(line 237, column 8)
            (_lhsOmorphisms@_) =
                _antcImorphisms ++ _consImorphisms
            -- "AGtry.ag"(line 276, column 8)
            (_lhsOsErr@_) =
                take 1
                 (_antcIsErr++ _consIsErr++
                  [ "8 in "++show rulePos_++"\n   Meaningless rule.\n"
                  | null _consIsigns&&null _antcIsigns]++
                  [ "1 in "++show rulePos_++"\n   Mismatch in rule:\n   "++
                    show _antcIexpr++ " :: "++shSigns _antcIsigns ++ "\n   does not match\n   "++
                    show _consIexpr++ " :: "++shSigns _consIsigns++"\n"
                  | null _is && not (null _antcIsigns) && not (null _consIsigns)]++
                  [ "2 in "++show rulePos_++"\n   Ambiguous types: "++shSigns _is++
                    "\n   in right hand side:  "++ show _consIexpr++
                    "\n   and left hand side:  "++ show _antcIexpr++"\n"
                  | length _is>1])
            -- "AGtry.ag"(line 461, column 8)
            (_lhsOrules@_) =
                [ _r ]
            -- "AGtry.ag"(line 459, column 8)
            (_r@_) =
                Ru c_ _antcIexpr rulePos_ _consIexpr expl_ (if null _is then error("Fatal: null @is on "++show rulePos_++"\n@antc.expr = "++show _antcIexpr++"\n@antc.signs = "++shSigns _antcIsigns++"\n@cons.expr = "++show _consIexpr++"\n@cons.signs = "++shSigns _consIsigns) else head _is) _lhsInr
            -- copy rule (down)
            (_antcOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_antcOmDef@_) =
                _lhsImDef
            -- copy rule (down)
            (_consOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_consOmDef@_) =
                _lhsImDef
        in  ( _lhsOmGen,_lhsOmorphisms,_lhsOrules,_lhsOsErr)
-- Rules -------------------------------------------------------
{-
   inherited attributes:
      gE                   : GenR
      mDef                 : Signatures

   chained attributes:
      nr                   : Int

   synthesised attributes:
      mGen                 : Gens
      morphisms            : [Morphism]
      rules                : Rules
      sErr                 : [String]

-}
{-
   local variables for Rules.Cons:

-}
{-
   local variables for Rules.Nil:

-}
-- semantic domain
type T_Rules = (GenR) ->
               (Signatures) ->
               (Int) ->
               ( (Gens),([Morphism]),(Int),(Rules),([String]))
-- cata
sem_Rules :: (Rules) ->
             (T_Rules)
sem_Rules (list) =
    (foldr (sem_Rules_Cons) (sem_Rules_Nil) ((map sem_Rule list)))
sem_Rules_Cons :: (T_Rule) ->
                  (T_Rules) ->
                  (T_Rules)
sem_Rules_Cons (hd_) (tl_) =
    \ _lhsIgE
      _lhsImDef
      _lhsInr ->
        let _lhsOmGen :: (Gens)
            _lhsOmorphisms :: ([Morphism])
            _lhsOnr :: (Int)
            _lhsOrules :: (Rules)
            _lhsOsErr :: ([String])
            _hdImGen :: (Gens)
            _hdImorphisms :: ([Morphism])
            _hdIrules :: (Rules)
            _hdIsErr :: ([String])
            _hdOgE :: (GenR)
            _hdOmDef :: (Signatures)
            _hdOnr :: (Int)
            _tlImGen :: (Gens)
            _tlImorphisms :: ([Morphism])
            _tlInr :: (Int)
            _tlIrules :: (Rules)
            _tlIsErr :: ([String])
            _tlOgE :: (GenR)
            _tlOmDef :: (Signatures)
            _tlOnr :: (Int)
            ( _hdImGen,_hdImorphisms,_hdIrules,_hdIsErr) =
                (hd_ (_hdOgE) (_hdOmDef) (_hdOnr))
            ( _tlImGen,_tlImorphisms,_tlInr,_tlIrules,_tlIsErr) =
                (tl_ (_tlOgE) (_tlOmDef) (_tlOnr))
            -- "AGtry.ag"(line 101, column 10)
            (_lhsOmGen@_) =
                _hdImGen ++ _tlImGen
            -- "AGtry.ag"(line 234, column 10)
            (_lhsOmorphisms@_) =
                _hdImorphisms ++ _tlImorphisms
            -- "AGtry.ag"(line 273, column 10)
            (_lhsOsErr@_) =
                _hdIsErr ++ _tlIsErr
            -- "AGtry.ag"(line 454, column 10)
            (_lhsOnr@_) =
                _tlInr
            -- "AGtry.ag"(line 453, column 10)
            (_tlOnr@_) =
                _lhsInr+1
            -- "AGtry.ag"(line 452, column 10)
            (_lhsOrules@_) =
                _hdIrules ++ _tlIrules
            -- copy rule (down)
            (_hdOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_hdOmDef@_) =
                _lhsImDef
            -- copy rule (down)
            (_hdOnr@_) =
                _lhsInr
            -- copy rule (down)
            (_tlOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_tlOmDef@_) =
                _lhsImDef
        in  ( _lhsOmGen,_lhsOmorphisms,_lhsOnr,_lhsOrules,_lhsOsErr)
sem_Rules_Nil :: (T_Rules)
sem_Rules_Nil  =
    \ _lhsIgE
      _lhsImDef
      _lhsInr ->
        let _lhsOmGen :: (Gens)
            _lhsOmorphisms :: ([Morphism])
            _lhsOnr :: (Int)
            _lhsOrules :: (Rules)
            _lhsOsErr :: ([String])
            -- "AGtry.ag"(line 102, column 10)
            (_lhsOmGen@_) =
                []
            -- "AGtry.ag"(line 235, column 10)
            (_lhsOmorphisms@_) =
                []
            -- "AGtry.ag"(line 274, column 10)
            (_lhsOsErr@_) =
                []
            -- "AGtry.ag"(line 456, column 10)
            (_lhsOnr@_) =
                _lhsInr
            -- "AGtry.ag"(line 455, column 10)
            (_lhsOrules@_) =
                []
        in  ( _lhsOmGen,_lhsOmorphisms,_lhsOnr,_lhsOrules,_lhsOsErr)
-- Signature ---------------------------------------------------
{-
   inherited attributes:
      gE                   : GenR

   chained attributes:

   synthesised attributes:
      nm                   : String
      sErr                 : [String]
      signature            : Signature

-}
{-
   local variables for Signature.Idn:

-}
{-
   local variables for Signature.Sgn:

-}
-- semantic domain
type T_Signature = (GenR) ->
                   ( (String),([String]),(Signature))
-- cata
sem_Signature :: (Signature) ->
                 (T_Signature)
sem_Signature ((Idn (_c) (_morPos))) =
    (sem_Signature_Idn ((sem_Concept (_c))) (_morPos))
sem_Signature ((Sgn (_nm) (_a) (_b) (_props) (_prL) (_prM) (_prR) (_content) (_morPos))) =
    (sem_Signature_Sgn (_nm) ((sem_Concept (_a))) ((sem_Concept (_b))) (_props) (_prL) (_prM) (_prR) (_content) (_morPos))
sem_Signature_Idn :: (T_Concept) ->
                     (FilePos) ->
                     (T_Signature)
sem_Signature_Idn (c_) (morPos_) =
    \ _lhsIgE ->
        let _lhsOnm :: (String)
            _lhsOsErr :: ([String])
            _lhsOsignature :: (Signature)
            _cIconcept :: (Concept)
            _cInm :: (String)
            _cOgE :: (GenR)
            ( _cIconcept,_cInm) =
                (c_ (_cOgE))
            -- "AGtry.ag"(line 379, column 9)
            (_lhsOsErr@_) =
                []
            -- "AGtry.ag"(line 515, column 9)
            (_lhsOnm@_) =
                "I"
            -- "AGtry.ag"(line 514, column 9)
            (_lhsOsignature@_) =
                Idn _cIconcept morPos_
            -- copy rule (down)
            (_cOgE@_) =
                _lhsIgE
        in  ( _lhsOnm,_lhsOsErr,_lhsOsignature)
sem_Signature_Sgn :: (String) ->
                     (T_Concept) ->
                     (T_Concept) ->
                     ([Prop]) ->
                     (String) ->
                     (String) ->
                     (String) ->
                     ([Link]) ->
                     (FilePos) ->
                     (T_Signature)
sem_Signature_Sgn (nm_) (a_) (b_) (props_) (prL_) (prM_) (prR_) (content_) (morPos_) =
    \ _lhsIgE ->
        let _lhsOnm :: (String)
            _lhsOsErr :: ([String])
            _lhsOsignature :: (Signature)
            _aIconcept :: (Concept)
            _aInm :: (String)
            _aOgE :: (GenR)
            _bIconcept :: (Concept)
            _bInm :: (String)
            _bOgE :: (GenR)
            ( _aIconcept,_aInm) =
                (a_ (_aOgE))
            ( _bIconcept,_bInm) =
                (b_ (_bOgE))
            -- "AGtry.ag"(line 371, column 9)
            (_lhsOsErr@_) =
                if _aInm == _bInm then [] else
                let ps = props_ `isc` [Trn,Rfx,Sym,Asy] in
                if null ps then []
                else ["9 in "++show morPos_++"\n   Heterogeneous relation "++
                      nm_++"["++ _aInm ++"*"++ _bInm ++
                      "]\n   may not be declared "++commaAnd [pMeaning p| p<-ps]++
                      ".\n   (This relation is heterogeneous because "++ _aInm ++" and "++ _bInm ++
                      "\n   are different concepts).\n"]
            -- "AGtry.ag"(line 513, column 9)
            (_lhsOnm@_) =
                nm_
            -- "AGtry.ag"(line 512, column 9)
            (_lhsOsignature@_) =
                Sgn nm_ _aIconcept _bIconcept props_ prL_ prM_ prR_ content_ morPos_
            -- copy rule (down)
            (_aOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_bOgE@_) =
                _lhsIgE
        in  ( _lhsOnm,_lhsOsErr,_lhsOsignature)
-- Signatures --------------------------------------------------
{-
   inherited attributes:
      gE                   : GenR

   chained attributes:

   synthesised attributes:
      sErr                 : [String]
      signatures           : Signatures

-}
{-
   local variables for Signatures.Cons:

-}
{-
   local variables for Signatures.Nil:

-}
-- semantic domain
type T_Signatures = (GenR) ->
                    ( ([String]),(Signatures))
-- cata
sem_Signatures :: (Signatures) ->
                  (T_Signatures)
sem_Signatures (list) =
    (foldr (sem_Signatures_Cons) (sem_Signatures_Nil) ((map sem_Signature list)))
sem_Signatures_Cons :: (T_Signature) ->
                       (T_Signatures) ->
                       (T_Signatures)
sem_Signatures_Cons (hd_) (tl_) =
    \ _lhsIgE ->
        let _lhsOsErr :: ([String])
            _lhsOsignatures :: (Signatures)
            _hdInm :: (String)
            _hdIsErr :: ([String])
            _hdIsignature :: (Signature)
            _hdOgE :: (GenR)
            _tlIsErr :: ([String])
            _tlIsignatures :: (Signatures)
            _tlOgE :: (GenR)
            ( _hdInm,_hdIsErr,_hdIsignature) =
                (hd_ (_hdOgE))
            ( _tlIsErr,_tlIsignatures) =
                (tl_ (_tlOgE))
            -- "AGtry.ag"(line 381, column 10)
            (_lhsOsErr@_) =
                _hdIsErr ++ _tlIsErr
            -- "AGtry.ag"(line 478, column 10)
            (_lhsOsignatures@_) =
                [m| m<-[ _hdIsignature], not (isIdent m)] ++ _tlIsignatures
            -- copy rule (down)
            (_hdOgE@_) =
                _lhsIgE
            -- copy rule (down)
            (_tlOgE@_) =
                _lhsIgE
        in  ( _lhsOsErr,_lhsOsignatures)
sem_Signatures_Nil :: (T_Signatures)
sem_Signatures_Nil  =
    \ _lhsIgE ->
        let _lhsOsErr :: ([String])
            _lhsOsignatures :: (Signatures)
            -- "AGtry.ag"(line 382, column 10)
            (_lhsOsErr@_) =
                []
            -- "AGtry.ag"(line 479, column 10)
            (_lhsOsignatures@_) =
                []
        in  ( _lhsOsErr,_lhsOsignatures)


