neato -Tpng Metamodels.dot -o Metamodels.png
neato -Tpng Metamodels_Objects.dot -o Metamodels_Objects.png
neato -Tpng Metamodels_Class_Diagram.dot -o Metamodels_Class_Diagram.png
neato -Tpng Metamodels_Rule_1.dot -o Metamodels_Rule_1.png
neato -Tpng Metamodels_Rule_2.dot -o Metamodels_Rule_2.png
neato -Tpng Metamodels_Rule_3.dot -o Metamodels_Rule_3.png
neato -Tpng MetamodelsObject.dot -o MetamodelsObject.png
neato -Tpng MetamodelsClass.dot -o MetamodelsClass.png
neato -Tpng MetamodelsAssociation.dot -o MetamodelsAssociation.png
neato -Tpng MetamodelsString.dot -o MetamodelsString.png
